import { useCallback,useEffect,useState } from 'react'
type Product={id:string;name:string;sku:string;category:string;salePriceCents:number|null;currency:string;pricingStatus:string;fulfillmentMode:string;images:readonly {url:string}[];variants:readonly unknown[]}
const stores=[['tenant-floes','FLOES'],['tenant-mg','MG Salud y Belleza'],['tenant-dgng','DGNG']] as const
const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
export function CatalogAdminPage(){
 const [tenant,setTenant]=useState<(typeof stores)[number][0]>('tenant-floes');const [access,setAccess]=useState(()=>sessionStorage.getItem('chopify-admin-access')??'');const [products,setProducts]=useState<readonly Product[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [name,setName]=useState('');const [sku,setSku]=useState('');const [category,setCategory]=useState('');const [price,setPrice]=useState('')
 const call=useCallback(async(operation:string,input:Record<string,unknown>={})=>{const response=await fetch('/api/commerce',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${access}`,'x-chopify-tenant-id':tenant},body:JSON.stringify({operation,input})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(response.status===401?'Ingresa una clave de administración válida.':body.error||'No fue posible cargar el catálogo');return body.data},[access,tenant])
 const load=useCallback(()=>{if(!access){setProducts([]);return}setLoading(true);setError('');void call('listProducts').then(setProducts).catch(cause=>setError(cause instanceof Error?cause.message:'No fue posible cargar el catálogo')).finally(()=>setLoading(false))},[access,call])
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer)},[load])
 const save=async()=>{const slug=slugify(name);if(!slug||!sku.trim()){setError('Nombre y SKU son obligatorios.');return}const parsed=price.trim()?Math.round(Number(price)*100):null;if(parsed!==null&&(!Number.isFinite(parsed)||parsed<=0)){setError('El precio debe ser positivo o quedar vacío.');return}sessionStorage.setItem('chopify-admin-access',access);setError('');try{await call('updateProduct',{product:{id:`${tenant}:${slug}`,tenantId:tenant,sku:sku.trim(),slug,name:name.trim(),description:'',commercialSummary:'',category:category.trim()||'Sin categoría',status:'ACTIVE',visibility:'VISIBLE',pricingStatus:parsed===null?'PENDING':'READY',costCents:null,percentage:null,percentageType:null,salePriceCents:parsed,currency:'COP',fulfillmentMode:'STOCK',images:[],variants:[]}});setName('');setSku('');setCategory('');setPrice('');load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible guardar el producto')}}
 return <main className="page"><div className="page-heading"><div><span className="eyebrow">Fuente comercial central</span><h1>Productos</h1><p>Cada tienda consume únicamente su catálogo persistido. La ausencia de productos se conserva como estado vacío.</p></div><label className="field compact-field"><span>Negocio</span><select value={tenant} onChange={event=>setTenant(event.target.value as typeof tenant)}>{stores.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div><section className="panel catalog-editor"><h2>Registrar producto</h2><div className="catalog-form"><label>Clave de administración<input type="password" value={access} onChange={event=>setAccess(event.target.value)}/></label><label>Nombre<input value={name} onChange={event=>setName(event.target.value)}/></label><label>SKU<input value={sku} onChange={event=>setSku(event.target.value)}/></label><label>Categoría<input value={category} onChange={event=>setCategory(event.target.value)}/></label><label>Precio COP (opcional)<input inputMode="decimal" value={price} onChange={event=>setPrice(event.target.value)}/></label><button className="primary-button" onClick={()=>void save()} disabled={!access||!name||!sku}>Guardar producto</button></div></section>{error&&<div className="error-banner">{error}</div>}{!loading&&products.length===0?<div className="commercial-empty"><strong>Sin productos reales</strong><p>Este negocio aún no tiene productos registrados.</p></div>:<section className="catalog-product-grid">{products.map(product=><article className="catalog-product panel" key={product.id}><div><small>{product.sku}</small><h2>{product.name}</h2><p>{product.category}</p><strong className="pending-price">{product.salePriceCents===null?'Precio pendiente':new Intl.NumberFormat('es-CO',{style:'currency',currency:product.currency,maximumFractionDigits:0}).format(product.salePriceCents/100)}</strong><span>{product.fulfillmentMode}</span></div></article>)}</section>}</main>
}
