import { useEffect,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
type Money={amount:number;currency:string}
type Image={url:string;alt:string}
type Variant={variantId:string;name:string;color?:string|null;sku:string;price:Money|null;pricingStatus:string;available:boolean;images:readonly Image[];fulfillmentMode:string}
type Product={productId:string;name:string;sku:string;slug:string;description:string;commercialSummary:string;category:string;price:Money|null;pricingStatus:string;available:boolean;imageUrl?:string;images:readonly Image[];fulfillmentMode:string;variants:readonly Variant[]}
const price=(money:Money|null)=>money?new Intl.NumberFormat('es-CO',{style:'currency',currency:money.currency,maximumFractionDigits:0}).format(money.amount):'Consultar precio'
export function StorefrontPage(){
 const {slug}=useParams();const [products,setProducts]=useState<readonly Product[]>([]);const [error,setError]=useState('')
 useEffect(()=>{fetch('/api/catalog').then(async(response)=>{if(!response.ok)throw new Error('No fue posible cargar el catálogo');return response.json() as Promise<readonly Product[]>}).then(setProducts).catch((cause:unknown)=>setError(cause instanceof Error?cause.message:'Catálogo no disponible'))},[])
 const selected=products.find((item)=>item.slug===slug)
 if(slug&&selected)return <ProductDetail product={selected}/>
 if(slug&&products.length&&!selected)return <main className="storefront"><p>Producto no encontrado.</p><Link to="/store">Volver al catálogo</Link></main>
 return <main className="storefront"><header className="store-head"><div><span>FLOES · Uniformes médicos</span><h1>Catálogo</h1><p>Modelos profesionales elaborados bajo pedido. El precio se confirma antes de realizar cualquier compra.</p></div></header>{error&&<div className="error-banner">{error}</div>}<section className="product-grid">{products.map((item)=><Link className="product-card" key={item.productId} to={`/store/${item.slug}`}><img src={item.imageUrl} alt={item.name}/><div><small>{item.category}</small><h2>{item.name}</h2><strong className={item.price?'':'pending-price'}>{price(item.price)}</strong><span>{item.fulfillmentMode==='MADE_TO_ORDER'?'Disponible bajo pedido':'Consultar disponibilidad'}</span></div></Link>)}</section></main>
}
function ProductDetail({product}:{product:Product}){
 const [variantId,setVariantId]=useState(product.variants[0]?.variantId??'');const variant=product.variants.find((item)=>item.variantId===variantId);const images=variant?.images.length?variant.images:product.images;const [imageUrl,setImageUrl]=useState(images[0]?.url??'')
 const selectVariant=(id:string)=>{const next=product.variants.find((item)=>item.variantId===id);setVariantId(id);setImageUrl(next?.images[0]?.url??product.images[0]?.url??'')}
 const shownPrice=variant?.price??product.price;const cta=shownPrice?'Solicitar compra':'Solicitar información'
 return <main className="storefront"><Link className="store-back" to="/store">← Catálogo FLOES</Link><section className="product-detail"><div className="product-gallery"><img className="product-hero-image" src={imageUrl} alt={variant?.color?`${product.name} ${variant.color}`:product.name}/><div>{images.map((item)=><button className={item.url===imageUrl?'active':''} key={item.url} onClick={()=>setImageUrl(item.url)}><img src={item.url} alt={item.alt}/></button>)}</div></div><div className="product-copy"><small>{product.category}</small><h1>{product.name}</h1><p>{product.description}</p>{product.variants.length>0&&<fieldset><legend>Color</legend><div className="variant-picker">{product.variants.map((item)=><button className={item.variantId===variantId?'active':''} onClick={()=>selectVariant(item.variantId)} key={item.variantId}>{item.color??item.name}</button>)}</div></fieldset>}<div className="store-price"><strong>{price(shownPrice)}</strong><span>{product.fulfillmentMode==='MADE_TO_ORDER'?'Elaboración bajo pedido. El tiempo se confirma al solicitar información.':''}</span></div><button className="store-cta" disabled={!shownPrice}>{cta}</button>{!shownPrice&&<p className="pricing-note">El precio está pendiente de confirmación. Podemos mostrarte las opciones y ayudarte a solicitar información.</p>}<dl><div><dt>SKU</dt><dd>{variant?.sku??product.sku}</dd></div><div><dt>Modalidad</dt><dd>Bajo pedido</dd></div></dl></div></section></main>
}
