import type { AutomationDefinition, AutomationEvaluation, AutomationExecution, AutomationPolicy, OutboxEvent } from '../../domain'
import type { AutomationDefinitionRepository, AutomationEvaluationRepository, AutomationExecutionRepository, AutomationPolicyRepository, OutboxRepository } from '../../repositories/automationContracts'
import { sampleAutomations, sampleAutomationPolicies, sampleOutbox } from '../../data/sample/automation'
export interface AutomationDatabase { automations:AutomationDefinition[]; policies:AutomationPolicy[]; evaluations:AutomationEvaluation[]; outbox:OutboxEvent[]; executions:AutomationExecution[] }
export const createAutomationDatabase=():AutomationDatabase=>({automations:sampleAutomations.map(x=>({...x,conditions:[...x.conditions],actions:[...x.actions]})),policies:sampleAutomationPolicies.map(x=>({...x})),evaluations:[],outbox:sampleOutbox.map(x=>({...x})),executions:[]})
const guard=(tenantId:string,item:{tenantId:string})=>{if(item.tenantId!==tenantId)throw new Error('Cross-tenant mutation rejected')}
const upsert=<T extends {id:string}>(xs:T[],x:T)=>{const i=xs.findIndex(v=>v.id===x.id);if(i>=0)xs[i]=x;else xs.push(x)}
export class MemoryAutomationDefinitionRepository implements AutomationDefinitionRepository { constructor(private db:AutomationDatabase){} async listByTenant(t:string){return this.db.automations.filter(x=>x.tenantId===t)} async getById(t:string,id:string){return this.db.automations.find(x=>x.tenantId===t&&x.id===id)??null} async save(t:string,x:AutomationDefinition){guard(t,x);upsert(this.db.automations,x)}}
export class MemoryAutomationPolicyRepository implements AutomationPolicyRepository { constructor(private db:AutomationDatabase){} async get(t:string){return this.db.policies.find(x=>x.tenantId===t)??null} async save(t:string,x:AutomationPolicy){guard(t,x);const i=this.db.policies.findIndex(v=>v.tenantId===t);if(i>=0)this.db.policies[i]=x;else this.db.policies.push(x)}}
export class MemoryAutomationEvaluationRepository implements AutomationEvaluationRepository { constructor(private db:AutomationDatabase){} async listByTenant(t:string){return this.db.evaluations.filter(x=>x.tenantId===t)} async append(t:string,x:AutomationEvaluation){guard(t,x);this.db.evaluations.push(x)}}
export class MemoryOutboxRepository implements OutboxRepository { constructor(private db:AutomationDatabase){} async listByTenant(t:string,f:Parameters<OutboxRepository['listByTenant']>[1]={}){return this.db.outbox.filter(x=>x.tenantId===t&&(!f?.status||x.status===f.status))} async getById(t:string,id:string){return this.db.outbox.find(x=>x.tenantId===t&&x.id===id)??null} async findBySourceAction(t:string,s:string,a:string,k:string){return this.db.outbox.find(x=>x.tenantId===t&&x.sourceEventId===s&&x.automationId===a&&x.actionType===k)??null} async save(t:string,x:OutboxEvent){guard(t,x);upsert(this.db.outbox,x)}}
export class MemoryAutomationExecutionRepository implements AutomationExecutionRepository { constructor(private db:AutomationDatabase){} async listByTenant(t:string){return this.db.executions.filter(x=>x.tenantId===t)} async append(t:string,x:AutomationExecution){guard(t,x);this.db.executions.push(x)}}
export function createSampleAutomationRepositories(db=createAutomationDatabase()){return{db,definitions:new MemoryAutomationDefinitionRepository(db),policies:new MemoryAutomationPolicyRepository(db),evaluations:new MemoryAutomationEvaluationRepository(db),outbox:new MemoryOutboxRepository(db),executions:new MemoryAutomationExecutionRepository(db)}}
