import type { AuditEvent, CommercialAgreement, IdempotencyRecord, IdempotentOperation, InventoryPosition, InventoryReservation, InventoryReservationItem, Order, Payment, PaymentProof } from '../../domain'
import { commitPosition, releasePosition, reservePosition } from '../../domain'
import type { AgreementRepository, AuditRepository, IdempotencyRepository, InventoryRepository, InventoryReservationRepository, OrderRepository, PaymentProofRepository, PaymentRepository } from '../../repositories/contracts'
import type { BusinessCommerceAdapter } from '../../application/commercePort'
import { sampleAgreements, sampleAuditEvents, sampleIdempotency, sampleInventory, sampleOrders, samplePayments, sampleProducts, sampleProofs, sampleReservations } from '../../data/sample/orders'

export interface SampleOrderDatabase { orders: Order[]; payments: Payment[]; proofs: PaymentProof[]; reservations: InventoryReservation[]; idempotency: IdempotencyRecord[]; inventory: InventoryPosition[]; agreements: CommercialAgreement[]; audit: AuditEvent[]; publishedOrderIds: string[] }
export const createSampleOrderDatabase = (): SampleOrderDatabase => ({
  orders: sampleOrders.map((item) => ({ ...item, items: item.items.map((line) => ({ ...line })), attributionSnapshot: { ...item.attributionSnapshot }, commercialAgreementSnapshot: item.commercialAgreementSnapshot ? { ...item.commercialAgreementSnapshot } : undefined, managedSnapshot: { ...item.managedSnapshot }, fulfillmentDetails: item.fulfillmentDetails ? { ...item.fulfillmentDetails } : undefined })),
  payments: samplePayments.map((item) => ({ ...item })),
  proofs: sampleProofs.map((item) => ({ ...item })),
  reservations: sampleReservations.map((item) => ({ ...item, items: item.items.map((line) => ({ ...line })) })),
  idempotency: sampleIdempotency.map((item) => ({ ...item })),
  inventory: sampleInventory.map((item) => ({ ...item })),
  agreements: sampleAgreements.map((item) => ({ ...item })),
  audit: sampleAuditEvents.map((item) => ({ ...item, metadata: item.metadata ? { ...item.metadata } : undefined })),
  publishedOrderIds: [],
})
const assertTenant = (tenantId: string, entity: { tenantId: string }) => { if (entity.tenantId !== tenantId) throw new Error('Cross-tenant mutation rejected') }
const upsert = <T extends { id: string }>(items: T[], entity: T) => { const index = items.findIndex((item) => item.id === entity.id); if (index < 0) items.push(entity); else items[index] = entity }
export class MemoryOrderRepository implements OrderRepository { constructor(private db: SampleOrderDatabase) {} async listByTenant(tenantId: string, filters: Parameters<OrderRepository['listByTenant']>[1] = {}) { const search = filters?.search?.toLowerCase(); return this.db.orders.filter((item) => item.tenantId === tenantId && (!filters?.orderStatus || item.orderStatus === filters.orderStatus) && (!filters?.paymentStatus || item.paymentStatus === filters.paymentStatus) && (!filters?.fulfillmentStatus || item.fulfillmentStatus === filters.fulfillmentStatus) && (filters?.managed === undefined || item.managedSnapshot.managed === filters.managed) && (!search || item.id.toLowerCase().includes(search) || item.customerId.toLowerCase().includes(search))) } async getById(tenantId: string, id: string) { return this.db.orders.find((item) => item.tenantId === tenantId && item.id === id) ?? null } async getByOpportunity(tenantId: string, opportunityId: string) { return this.db.orders.find((item) => item.tenantId === tenantId && item.opportunityId === opportunityId) ?? null } async save(tenantId: string, item: Order) { assertTenant(tenantId, item); upsert(this.db.orders, item) } }
export class MemoryPaymentRepository implements PaymentRepository { constructor(private db: SampleOrderDatabase) {} async listByTenant(tenantId: string, filters: Parameters<PaymentRepository['listByTenant']>[1] = {}) { return this.db.payments.filter((item) => item.tenantId === tenantId && (!filters?.status || item.status === filters.status)) } async getById(tenantId: string, id: string) { return this.db.payments.find((item) => item.tenantId === tenantId && item.id === id) ?? null } async getByOrder(tenantId: string, orderId: string) { return this.db.payments.find((item) => item.tenantId === tenantId && item.orderId === orderId) ?? null } async save(tenantId: string, item: Payment) { assertTenant(tenantId, item); upsert(this.db.payments, item) } }
export class MemoryProofRepository implements PaymentProofRepository { constructor(private db: SampleOrderDatabase) {} async listByTenant(tenantId: string, filters: Parameters<PaymentProofRepository['listByTenant']>[1] = {}) { return this.db.proofs.filter((item) => item.tenantId === tenantId && (!filters?.status || item.status === filters.status) && (!filters?.orderId || item.orderId === filters.orderId)) } async getById(tenantId: string, id: string) { return this.db.proofs.find((item) => item.tenantId === tenantId && item.id === id) ?? null } async save(tenantId: string, item: PaymentProof) { assertTenant(tenantId, item); upsert(this.db.proofs, item) } }
export class MemoryReservationRepository implements InventoryReservationRepository { constructor(private db: SampleOrderDatabase) {} async listByTenant(tenantId: string, filters: Parameters<InventoryReservationRepository['listByTenant']>[1] = {}) { return this.db.reservations.filter((item) => item.tenantId === tenantId && (!filters?.status || item.status === filters.status)) } async getById(tenantId: string, id: string) { return this.db.reservations.find((item) => item.tenantId === tenantId && item.id === id) ?? null } async getByOrder(tenantId: string, orderId: string) { return this.db.reservations.find((item) => item.tenantId === tenantId && item.orderId === orderId) ?? null } async save(tenantId: string, item: InventoryReservation) { assertTenant(tenantId, item); upsert(this.db.reservations, item) } }
export class MemoryIdempotencyRepository implements IdempotencyRepository { constructor(private db: SampleOrderDatabase) {} async get(tenantId: string, operation: IdempotentOperation, key: string) { return this.db.idempotency.find((item) => item.tenantId === tenantId && item.operation === operation && item.key === key) ?? null } async save(tenantId: string, item: IdempotencyRecord) { assertTenant(tenantId, item); const duplicate = await this.get(tenantId, item.operation, item.key); if (duplicate) Object.assign(duplicate, item); else this.db.idempotency.push(item) } }
export class MemoryAgreementRepository implements AgreementRepository { constructor(private db: SampleOrderDatabase) {} async getEffective(tenantId: string, at: string) { return this.db.agreements.filter((item) => item.tenantId === tenantId && item.effectiveFrom <= at && (!item.effectiveTo || item.effectiveTo > at)).sort((a,b) => b.effectiveFrom.localeCompare(a.effectiveFrom))[0] ?? null } }
export class MemoryAuditRepository implements AuditRepository { constructor(private db: SampleOrderDatabase) {} async listByTenant(tenantId: string, filters: Parameters<AuditRepository['listByTenant']>[1] = {}) { return this.db.audit.filter((item) => item.tenantId === tenantId && (!filters?.entityType || item.entityType === filters.entityType) && (!filters?.entityId || item.entityId === filters.entityId)) } async append(tenantId: string, item: AuditEvent) { assertTenant(tenantId, item); this.db.audit.push(item) } }
export class SampleBusinessCommerceAdapter implements BusinessCommerceAdapter, InventoryRepository {
  constructor(private db: SampleOrderDatabase) {}
  async searchProducts(tenantId: string, query: string) { const normalized = query.toLowerCase(); return sampleProducts.filter((item) => item.tenantId === tenantId && item.name.toLowerCase().includes(normalized)).map((item) => ({ ...item, available: this.availability(item.tenantId, item.id, item.variantId) })) }
  async getProduct(tenantId: string, productId: string, variantId?: string) { const item = sampleProducts.find((entry) => entry.tenantId === tenantId && entry.id === productId && entry.variantId === variantId); return item ? { ...item, available: this.availability(tenantId, productId, variantId) } : null }
  async getPrice(tenantId: string, productId: string, variantId?: string) { const item = await this.getProduct(tenantId, productId, variantId); return item ? { priceCents: item.priceCents, currency: item.currency } : null }
  async getAvailability(tenantId: string, productId: string, variantId?: string) { return this.availability(tenantId, productId, variantId) }
  async getPosition(tenantId: string, productId: string, variantId?: string) { return this.db.inventory.find((item) => item.tenantId === tenantId && item.productId === productId && item.variantId === variantId) ?? null }
  private availability(tenantId: string, productId: string, variantId?: string) { const item = this.db.inventory.find((entry) => entry.tenantId === tenantId && entry.productId === productId && entry.variantId === variantId); return item ? Math.max(0, item.onHand - item.reserved) : 0 }
  private async mutate(tenantId: string, items: readonly InventoryReservationItem[], change: (position: InventoryPosition, amount: number) => InventoryPosition) { const positions = items.map((item) => { const position = this.db.inventory.find((entry) => entry.tenantId === tenantId && entry.productId === item.productId && entry.variantId === item.variantId); if (!position) throw new Error('Inventory position not found in tenant'); return { item, position, next: change(position, item.quantity) } }); for (const { position, next } of positions) Object.assign(position, next); return positions.map(({ next }) => next) }
  reserveInventory(tenantId: string, items: readonly InventoryReservationItem[]) { return this.mutate(tenantId, items, reservePosition) }
  releaseInventory(tenantId: string, items: readonly InventoryReservationItem[]) { return this.mutate(tenantId, items, releasePosition) }
  commitInventory(tenantId: string, items: readonly InventoryReservationItem[]) { return this.mutate(tenantId, items, commitPosition) }
  async publishOrderReference(tenantId: string, orderId: string) { const order = this.db.orders.find((item) => item.tenantId === tenantId && item.id === orderId); if (!order) throw new Error('Order not found in tenant'); if (!this.db.publishedOrderIds.includes(orderId)) this.db.publishedOrderIds.push(orderId) }
}
export function createSampleOrderRepositories(db = createSampleOrderDatabase()) { const commerce = new SampleBusinessCommerceAdapter(db); return { db, orders: new MemoryOrderRepository(db), payments: new MemoryPaymentRepository(db), proofs: new MemoryProofRepository(db), reservations: new MemoryReservationRepository(db), idempotency: new MemoryIdempotencyRepository(db), agreements: new MemoryAgreementRepository(db), audit: new MemoryAuditRepository(db), inventory: commerce as InventoryRepository, commerce } }
