/* eslint-disable react-hooks/set-state-in-effect -- loaders await authenticated network I/O before updating state */
import { useCallback, useEffect, useState } from 'react'
import type { Order, Payment, PaymentProof } from '../../domain/order'
import { adminCall } from '../../services/adminApi'
import { useUIStore } from '../../stores/uiStore'

type Tenant = { id: string; name: string; slug: string; status: string }
type DashboardRow = { tenantId: string; summary: { orders: number; paymentsToVerify: number }; preparing: number; ready: number; dispatched: number; delivered: number; managedRevenueCents: number | null; managedRevenueCurrency?: string | null; revenueByCurrency?: Record<string, number>; currencyStatus?: 'NO_REVENUE' | 'SINGLE' | 'MIXED' }
type Review = { proof: PaymentProof; payment: Payment; order: Order }
const ids = ['tenant-floes', 'tenant-mg', 'tenant-dgng']
const currency = (value: number, currencyCode: string) => new Intl.NumberFormat('es-EC', { style: 'currency', currency: currencyCode, maximumFractionDigits: 2 }).format(value / 100)
function Scope() { const value = useUIStore(s => s.tenantScope); const set = useUIStore(s => s.setTenantScope); return <select value={value} onChange={event => set(event.target.value)}><option value="all">Todos los negocios</option><option value="tenant-floes">FLOES</option><option value="tenant-mg">MG</option><option value="tenant-dgng">DGNG</option></select> }
const selected = (scope: string) => scope === 'all' ? ids : [scope]

export function RealDashboardPage() {
  const scope = useUIStore(s => s.tenantScope); const [rows, setRows] = useState<DashboardRow[]>([]); const [error, setError] = useState('')
  useEffect(() => { void adminCall<DashboardRow[]>('dashboard', scope).then(setRows).catch(e => setError(e instanceof Error ? e.message : 'Datos no disponibles')) }, [scope])
  const revenueCurrency = rows.find(r => r.managedRevenueCurrency)?.managedRevenueCurrency ?? null; const revenueAvailable = rows.every(row => row.managedRevenueCents !== null)
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Business Center · producción</span><h1>Command Center</h1><p>Consolidado persistido. Utilidad, margen y conversión permanecen no disponibles sin datos suficientes.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="h3-summary-grid"><article><span>Pedidos</span><strong>{rows.reduce((s, r) => s + r.summary.orders, 0)}</strong></article><article><span>Revisión de pago</span><strong>{rows.reduce((s, r) => s + r.summary.paymentsToVerify, 0)}</strong></article><article><span>Revenue gestionado</span><strong>{revenueAvailable ? revenueCurrency ? currency(rows.reduce((s, r) => s + (r.managedRevenueCents ?? 0), 0), revenueCurrency) : 'No disponible' : 'No disponible'}</strong></article><article><span>Utilidad / margen</span><strong>No disponible</strong></article></section><section className="panel"><h2>Estado por tenant</h2>{rows.map(row => <p key={row.tenantId}><strong>{row.tenantId}</strong> · preparando {row.preparing} · listos {row.ready} · despachados {row.dispatched} · entregados {row.delivered}</p>)}</section></div>
}
export function RealBusinessesPage() { const [rows, setRows] = useState<Tenant[]>([]); const [error, setError] = useState(''); useEffect(() => { void adminCall<Tenant[]>('listTenants').then(setRows).catch(e => setError(e instanceof Error ? e.message : 'No disponible')) }, []); return <div className="page"><div className="page-heading"><div><span className="eyebrow">Tenant Center</span><h1>Negocios</h1><p>Onboarding no implica una integración activa.</p></div></div>{error && <div className="error-banner">{error}</div>}<div className="platform-grid">{rows.map(row => <article className="platform-card" key={row.id}><h2>{row.name}</h2><p>{row.id}</p><span className={`entity-status status-${row.status.toLowerCase()}`}>{row.status}</span></article>)}</div></div> }
export function RealOrdersPage() { const scope = useUIStore(s => s.tenantScope); const [items, setItems] = useState<Order[]>([]); const [error, setError] = useState(''); const load = useCallback(async () => { try { setItems((await Promise.all(selected(scope).map(id => adminCall<Order[]>('listOrders', id)))).flat()) } catch (e) { setError(e instanceof Error ? e.message : 'No disponible') } }, [scope]); useEffect(() => { void load() }, [load]); return <div className="page"><div className="page-heading"><div><span className="eyebrow">Operations Center</span><h1>Pedidos</h1><p>Pedidos persistidos y aislados por tenant.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="panel">{items.length === 0 ? <p>Sin pedidos reales.</p> : items.map(order => <p key={`${order.tenantId}:${order.id}`}><strong>{order.id}</strong> · {order.tenantId} · {order.paymentStatus} · {order.fulfillmentStatus} · {currency(order.grandTotalCents, order.currency)}</p>)}</section></div> }
export function RealPaymentReviewPage() { const scope = useUIStore(s => s.tenantScope); const [items, setItems] = useState<Review[]>([]); const [error, setError] = useState(''); const load = useCallback(async () => { try { setItems((await Promise.all(selected(scope).map(id => adminCall<Review[]>('listPaymentReviews', id)))).flat()) } catch (e) { setError(e instanceof Error ? e.message : 'No disponible') } }, [scope]); useEffect(() => { void load() }, [load]); async function act(operation: string, review: Review, reason?: string) { try { await adminCall(operation, review.order.tenantId, { paymentId: review.payment.id, proofId: review.proof.id, reason }, crypto.randomUUID()); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Operación fallida') } } return <div className="page"><div className="page-heading"><div><span className="eyebrow">Control humano</span><h1>Revisión de pagos</h1><p>El comprobante es evidencia pendiente; GanoBot nunca aprueba pagos.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="panel">{items.length === 0 ? <p>Sin comprobantes pendientes.</p> : items.map(review => <article key={review.proof.id}><strong>{review.order.id} · {currency(review.payment.amountCents, review.payment.currency)}</strong> <button className="primary-button" onClick={() => void act('approvePayment', review)}>Aprobar</button> <button className="secondary-button" onClick={() => { const reason = window.prompt('Motivo del rechazo'); if (reason?.trim()) void act('rejectPaymentProof', review, reason) }}>Rechazar</button></article>)}</section></div> }
export function RealFulfillmentPage() { const scope = useUIStore(s => s.tenantScope); const [items, setItems] = useState<Order[]>([]); const [error, setError] = useState(''); const load = useCallback(async () => { try { const all = (await Promise.all(selected(scope).map(id => adminCall<Order[]>('listOrders', id)))).flat(); setItems(all.filter(o => o.paymentStatus === 'PAID' && !['DELIVERED', 'CANCELLED'].includes(o.fulfillmentStatus))) } catch (e) { setError(e instanceof Error ? e.message : 'No disponible') } }, [scope]); useEffect(() => { void load() }, [load]); async function advance(order: Order) { const operation = ({ UNFULFILLED: 'startPreparation', PREPARING: 'markReady', READY: 'dispatchOrder', DISPATCHED: 'markDelivered' } as Record<string, string>)[order.fulfillmentStatus]; if (!operation) return; try { const input: Record<string, unknown> = { orderId: order.id }; if (operation === 'dispatchOrder') { input.courier = window.prompt('Courier (opcional)') || undefined; input.trackingCode = window.prompt('Tracking (opcional)') || undefined } await adminCall(operation, order.tenantId, input, crypto.randomUUID()); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Operación fallida') } } return <div className="page"><div className="page-heading"><div><span className="eyebrow">Operations Center</span><h1>Fulfillment</h1><p>Las transiciones son validadas por el dominio.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="panel">{items.length === 0 ? <p>Sin pedidos pagados pendientes.</p> : items.map(order => <p key={`${order.tenantId}:${order.id}`}><strong>{order.id}</strong> · {order.fulfillmentStatus} <button className="primary-button" onClick={() => void advance(order)}>Avanzar</button></p>)}</section></div> }
export function IntegrationsPage() { const [data, setData] = useState<Record<string, string>>({}); const [error, setError] = useState(''); useEffect(() => { void adminCall<Record<string, string>>('integrationStatus').then(setData).catch(e => setError(e instanceof Error ? e.message : 'No disponible')) }, []); return <div className="page"><div className="page-heading"><div><span className="eyebrow">Integrations Center</span><h1>Integraciones</h1><p>Estado por presencia de configuración server-side; no se exponen valores.</p></div></div>{error && <div className="error-banner">{error}</div>}<section className="panel">{Object.entries(data).map(([name, status]) => <p key={name}><strong>{name}</strong> · {status}</p>)}</section></div> }
