/* eslint-disable react-hooks/set-state-in-effect -- loaders await authenticated network I/O before updating state */
import { useCallback, useEffect, useState } from 'react'
import type { Order, Payment, PaymentProof } from '../../domain/order'
import type { Customer } from '../../domain/customer'
import type { Opportunity } from '../../domain/opportunity'
import type { SupervisorSnapshot } from '../../domain/supervisor'
import { adminCall } from '../../services/adminApi'
import { useUIStore } from '../../stores/uiStore'
import { tenantDefinitions, tenantIds } from '../../config/tenantRegistry.js'

type Tenant = { id: string; name: string; slug: string; status: string }
type DashboardRow = { tenantId: string; summary: { orders: number; paymentsToVerify: number }; preparing: number; ready: number; dispatched: number; delivered: number; managedRevenueCents: number | null; managedRevenueCurrency?: string | null; revenueByCurrency?: Record<string, number>; currencyStatus?: 'NO_REVENUE' | 'SINGLE' | 'MIXED'; conversion: number | null; conversionBasis: number }
type Review = { proof: PaymentProof; payment: Payment; order: Order }
type AdminOrder = Order & { customer?: { customerId: string; name: string; phone?: string; email?: string } | null }
const currency = (value: number, currencyCode: string) => new Intl.NumberFormat('es-EC', { style: 'currency', currency: currencyCode, maximumFractionDigits: 2 }).format(value / 100)
const safeExternalLink = (value?: string) => {
  if (!value) return null
  try { const url = new URL(value); return ['https:', 'http:'].includes(url.protocol) ? url.toString() : null }
  catch { return null }
}
function Scope() { const value = useUIStore(s => s.tenantScope); const set = useUIStore(s => s.setTenantScope); return <select value={value} onChange={event => set(event.target.value)}><option value="all">Todos los negocios</option>{tenantIds.map(id=><option key={id} value={id}>{tenantDefinitions[id].name}</option>)}</select> }
const selected = (scope: string) => scope === 'all' ? tenantIds : [scope]

export function RealDashboardPage() {
  const scope = useUIStore(s => s.tenantScope); const [rows, setRows] = useState<DashboardRow[]>([]); const [error, setError] = useState(''); const [loading,setLoading]=useState(true)
  useEffect(() => { setLoading(true);setError('');void adminCall<DashboardRow[]>('dashboard', scope).then(setRows).catch(e => {setRows([]);setError(e instanceof Error ? e.message : 'Datos no disponibles')}).finally(()=>setLoading(false)) }, [scope])
  const revenueByCurrency=rows.reduce<Record<string,number>>((totals,row)=>{for(const [code,cents] of Object.entries(row.revenueByCurrency??{}))totals[code]=(totals[code]??0)+cents;return totals},{})
  const revenueEntries=Object.entries(revenueByCurrency)
  const revenueLabel=loading?'Cargando…':revenueEntries.length===0?'Sin ingresos administrados':revenueEntries.map(([code,cents])=>currency(cents,code)).join(' · ')
  const conversionBasis=rows.reduce((sum,row)=>sum+row.conversionBasis,0);const convertedWins=rows.reduce((sum,row)=>sum+(row.conversion===null?0:row.conversion*row.conversionBasis),0);const conversionLabel=loading?'Cargando…':conversionBasis===0?'No disponible':`${new Intl.NumberFormat('es-EC',{style:'percent',maximumFractionDigits:1}).format(convertedWins/conversionBasis)} (${conversionBasis} cerradas)`
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Business Center · producción</span><h1>Command Center</h1><p>Consolidado persistido. Utilidad, margen y conversión permanecen no disponibles sin datos suficientes.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="h3-summary-grid"><article><span>Pedidos</span><strong>{loading?'Cargando…':rows.reduce((s, r) => s + r.summary.orders, 0)}</strong></article><article><span>Revisión de pago</span><strong>{loading?'Cargando…':rows.reduce((s, r) => s + r.summary.paymentsToVerify, 0)}</strong></article><article><span>Revenue gestionado</span><strong>{revenueLabel}</strong></article><article><span>Conversión</span><strong>{conversionLabel}</strong></article><article><span>Utilidad / margen</span><strong>No disponible</strong></article></section><section className="panel"><h2>Estado por tenant</h2>{loading?<p>Cargando datos persistidos…</p>:rows.length===0&&!error?<p>Sin datos persistidos.</p>:rows.map(row => <p key={row.tenantId}><strong>{row.tenantId}</strong> · preparando {row.preparing} · listos {row.ready} · despachados {row.dispatched} · entregados {row.delivered}</p>)}</section></div>
}
export function RealBusinessesPage() { const [rows, setRows] = useState<Tenant[]>([]); const [error, setError] = useState(''); useEffect(() => { void adminCall<Tenant[]>('listTenants').then(setRows).catch(e => setError(e instanceof Error ? e.message : 'No disponible')) }, []); return <div className="page"><div className="page-heading"><div><span className="eyebrow">Tenant Center</span><h1>Negocios</h1><p>Onboarding no implica una integración activa.</p></div></div>{error && <div className="error-banner">{error}</div>}<div className="platform-grid">{rows.map(row => <article className="platform-card" key={row.id}><h2>{row.name}</h2><p>{row.id}</p><span className={`entity-status status-${row.status.toLowerCase()}`}>{row.status}</span></article>)}</div></div> }
export function RealOrdersPage() { const scope = useUIStore(s => s.tenantScope); const [items, setItems] = useState<AdminOrder[]>([]); const [error, setError] = useState(''); const [loading,setLoading]=useState(true); const load = useCallback(async () => { setLoading(true);setError('');try { setItems((await Promise.all(selected(scope).map(id => adminCall<AdminOrder[]>('listOrders', id)))).flat()) } catch (e) { setItems([]);setError(e instanceof Error ? e.message : 'No disponible') } finally {setLoading(false)} }, [scope]); useEffect(() => { void load() }, [load]); return <div className="page"><div className="page-heading"><div><span className="eyebrow">Operations Center</span><h1>Pedidos</h1><p>Pedidos persistidos, sus líneas y estados autoritativos, aislados por tenant.</p></div><Scope /></div>{error && <div className="error-banner">{error} <button onClick={()=>void load()}>Reintentar</button></div>}<section className="panel admin-record-list">{loading?<p>Cargando pedidos…</p>:items.length === 0 ? <p>Sin pedidos reales.</p> : items.map(order => <article key={`${order.tenantId}:${order.id}`}><header><div><strong>{order.id}</strong><small>{order.tenantId} · {order.customer?.name ?? order.customerId} · {new Date(order.createdAt).toLocaleString('es-EC')}</small></div><b>{currency(order.grandTotalCents, order.currency)}</b></header><p>{order.items.map(item=>`${item.quantity} × ${item.productName}${item.variantName?` (${item.variantName})`:''}`).join(' · ')}</p><footer><span className="entity-status">Pago: {order.paymentStatus}</span><span className="entity-status">Fulfillment: {order.fulfillmentStatus}</span><span>{order.currency}</span></footer></article>)}</section></div> }
export function RealPaymentReviewPage() { const scope = useUIStore(s => s.tenantScope); const [items, setItems] = useState<Review[]>([]); const [error, setError] = useState(''); const [busy,setBusy]=useState(''); const load = useCallback(async () => { setError('');try { setItems((await Promise.all(selected(scope).map(id => adminCall<Review[]>('listPaymentReviews', id)))).flat()) } catch (e) { setItems([]);setError(e instanceof Error ? e.message : 'No disponible') } }, [scope]); useEffect(() => { void load() }, [load]); async function act(operation: string, review: Review, reason?: string) { setBusy(review.proof.id);try { await adminCall(operation, review.order.tenantId, { paymentId: review.payment.id, proofId: review.proof.id, reason }, crypto.randomUUID()); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Operación fallida') } finally {setBusy('')} } return <div className="page"><div className="page-heading"><div><span className="eyebrow">Control humano</span><h1>Revisión de pagos</h1><p>El comprobante es evidencia pendiente; GanoBot nunca aprueba pagos.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="panel admin-record-list">{items.length === 0 ? <p>Sin comprobantes pendientes.</p> : items.map(review => {const proofLink=safeExternalLink(review.proof.assetReference);return <article key={review.proof.id}><header><div><strong>{review.order.id}</strong><small>{review.order.tenantId} · recibido {new Date(review.proof.submittedAt).toLocaleString('es-EC')}</small></div><b>{currency(review.payment.amountCents, review.payment.currency)}</b></header><p>Referencia: {review.proof.reference || 'No indicada'} · Tipo: {review.proof.type} · Estado: {review.proof.status}</p>{proofLink&&<a className="text-link" href={proofLink} target="_blank" rel="noreferrer">Abrir comprobante</a>}<footer><button disabled={busy===review.proof.id} className="primary-button" onClick={() => void act('approvePayment', review)}>Aprobar</button><button disabled={busy===review.proof.id} className="secondary-button" onClick={() => { const reason = window.prompt('Motivo del rechazo'); if (reason?.trim()) void act('rejectPaymentProof', review, reason) }}>Rechazar</button></footer></article>})}</section></div> }
export function RealFulfillmentPage() { const scope = useUIStore(s => s.tenantScope); const [items, setItems] = useState<Order[]>([]); const [error, setError] = useState(''); const [busy,setBusy]=useState(''); const load = useCallback(async () => { setError('');try { const all = (await Promise.all(selected(scope).map(id => adminCall<Order[]>('listOrders', id)))).flat(); setItems(all.filter(o => o.paymentStatus === 'PAID' && !['DELIVERED', 'CANCELLED'].includes(o.fulfillmentStatus))) } catch (e) { setItems([]);setError(e instanceof Error ? e.message : 'No disponible') } }, [scope]); useEffect(() => { void load() }, [load]); async function advance(order: Order) { const operation = ({ UNFULFILLED: 'startPreparation', PREPARING: 'markReady', READY: 'dispatchOrder', DISPATCHED: 'markDelivered' } as Record<string, string>)[order.fulfillmentStatus]; if (!operation) return; setBusy(order.id);try { const input: Record<string, unknown> = { orderId: order.id }; if (operation === 'dispatchOrder') { input.courier = window.prompt('Courier (opcional)') || undefined; input.trackingCode = window.prompt('Tracking (opcional)') || undefined } await adminCall(operation, order.tenantId, input, crypto.randomUUID()); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Operación fallida') } finally {setBusy('')} } const labels:Record<string,string>={UNFULFILLED:'Preparar',PREPARING:'Marcar listo',READY:'Despachar',DISPATCHED:'Marcar entregado'}; return <div className="page"><div className="page-heading"><div><span className="eyebrow">Operations Center</span><h1>Fulfillment</h1><p>Sólo se presenta la siguiente transición válida; el backend conserva la autoridad.</p></div><Scope /></div>{error && <div className="error-banner">{error}</div>}<section className="panel admin-record-list">{items.length === 0 ? <p>Sin pedidos pagados pendientes.</p> : items.map(order => <article key={`${order.tenantId}:${order.id}`}><header><div><strong>{order.id}</strong><small>{order.tenantId} · {order.items.reduce((sum,item)=>sum+item.quantity,0)} unidades</small></div><span className="entity-status">{order.fulfillmentStatus}</span></header><footer><button disabled={busy===order.id} className="primary-button" onClick={() => void advance(order)}>{labels[order.fulfillmentStatus]}</button></footer></article>)}</section></div> }

export function RealCustomersPage(){const scope=useUIStore(s=>s.tenantScope);const [items,setItems]=useState<Customer[]>([]);const [error,setError]=useState('');useEffect(()=>{setError('');void Promise.all(selected(scope).map(id=>adminCall<Customer[]>('listCustomers',id))).then(rows=>setItems(rows.flat())).catch(e=>{setItems([]);setError(e instanceof Error?e.message:'No disponible')})},[scope]);return <div className="page"><div className="page-heading"><div><span className="eyebrow">Client Center</span><h1>Clientes</h1><p>Identidades persistidas del tenant seleccionado, sin CRM paralelo.</p></div><Scope/></div>{error&&<div className="error-banner">{error}</div>}<section className="panel admin-record-list">{items.length===0?<p>Sin clientes persistidos.</p>:items.map(item=><article key={`${item.tenantId}:${item.id}`}><header><div><strong>{item.name}</strong><small>{item.tenantId} · {item.id}</small></div><span className="entity-status">{item.status}</span></header><p>{[item.phone,item.email].filter(Boolean).join(' · ')||'Sin canal de contacto registrado'}</p>{item.acquisitionSource&&<footer><span>Origen: {item.acquisitionSource}</span></footer>}</article>)}</section></div>}

export function RealOpportunitiesPage(){const scope=useUIStore(s=>s.tenantScope);const [items,setItems]=useState<Opportunity[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [error,setError]=useState('');useEffect(()=>{setError('');void Promise.all(selected(scope).flatMap(id=>[adminCall<Opportunity[]>('listOpportunities',id),adminCall<Customer[]>('listCustomers',id)])).then(rows=>{setItems(rows.filter((_,index)=>index%2===0).flat() as Opportunity[]);setCustomers(rows.filter((_,index)=>index%2===1).flat() as Customer[])}).catch(e=>{setItems([]);setCustomers([]);setError(e instanceof Error?e.message:'No disponible')})},[scope]);const customerName=(item:Opportunity)=>customers.find(customer=>customer.tenantId===item.tenantId&&customer.id===item.customerId)?.name??item.customerId;return <div className="page"><div className="page-heading"><div><span className="eyebrow">Commercial pipeline</span><h1>Oportunidades</h1><p>Estados comerciales persistidos y asociados a su cliente real.</p></div><Scope/></div>{error&&<div className="error-banner">{error}</div>}<section className="panel admin-record-list">{items.length===0?<p>Sin oportunidades persistidas.</p>:items.map(item=><article key={`${item.tenantId}:${item.id}`}><header><div><strong>{customerName(item)}</strong><small>{item.tenantId} · {item.intent.replaceAll('_',' ')}</small></div><b>{currency(item.estimatedValueCents,item.currency)}</b></header><footer><span className="entity-status">{item.status}</span><span>{item.id}</span></footer></article>)}</section></div>}

export function RealExceptionsPage(){const scope=useUIStore(s=>s.tenantScope);const [snapshots,setSnapshots]=useState<SupervisorSnapshot[]>([]);const [error,setError]=useState('');useEffect(()=>{setError('');void Promise.all(selected(scope).map(id=>adminCall<SupervisorSnapshot>('listExceptions',id))).then(setSnapshots).catch(e=>{setSnapshots([]);setError(e instanceof Error?e.message:'No disponible')})},[scope]);const items=snapshots.flatMap(snapshot=>snapshot.humanQueue);return <div className="page"><div className="page-heading"><div><span className="eyebrow">Operations Center</span><h1>Excepciones</h1><p>Escalaciones y problemas reales que requieren atención humana.</p></div><Scope/></div>{error&&<div className="error-banner">{error}</div>}<section className="panel admin-record-list">{items.length===0?<p>Sin excepciones abiertas.</p>:items.map(item=><article key={`${item.tenantId}:${item.conversationId}`}><header><div><strong>{item.summary}</strong><small>{item.tenantId} · conversación {item.conversationId}</small></div><span className="entity-status">{item.priority}</span></header><footer><span>{item.state.replaceAll('_',' ')}</span>{item.reason&&<span>{item.reason.replaceAll('_',' ')}</span>}{item.orderId&&<span>Pedido {item.orderId}</span>}</footer></article>)}</section></div>}
export function IntegrationsPage() { const [data, setData] = useState<Record<string, string>>({}); const [error, setError] = useState(''); useEffect(() => { void adminCall<Record<string, string>>('integrationStatus').then(setData).catch(e => setError(e instanceof Error ? e.message : 'No disponible')) }, []); return <div className="page"><div className="page-heading"><div><span className="eyebrow">Integrations Center</span><h1>Integraciones</h1><p>Estado por presencia de configuración server-side; no se exponen valores.</p></div></div>{error && <div className="error-banner">{error}</div>}<section className="panel">{Object.entries(data).map(([name, status]) => <p key={name}><strong>{name}</strong> · {status}</p>)}</section></div> }
