import { ArrowLeft, RotateCcw, UserRoundCheck, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { sampleCommercialApp } from '../../application/sampleApp'
import type { CommercialActivity, Conversation, Customer, Opportunity } from '../../domain'
import { date, money, SampleBadge, StatusPill, tenantNames } from '../commercial/shared'

export function ConversationDetailPage() {
  const { tenantId = '', conversationId = '' } = useParams()
  const [item, setItem] = useState<Conversation | null>(null)
  const [customer, setCustomer] = useState<Customer | null>(null)
  const [opportunities, setOpportunities] = useState<readonly Opportunity[]>([])
  const [activities, setActivities] = useState<readonly CommercialActivity[]>([])
  const [error, setError] = useState('')
  const load = useCallback(() => { setError(''); void sampleCommercialApp.getConversation(tenantId, conversationId).then(async (next) => { setItem(next); if (next) { const [detail, linked, timeline] = await Promise.all([sampleCommercialApp.getCustomerDetail(tenantId, next.customerId), sampleCommercialApp.listOpportunities(tenantId), sampleCommercialApp.listCommercialActivities(tenantId, { conversationId })]); setCustomer(detail?.customer ?? null); setOpportunities(linked.filter((opportunity) => opportunity.conversationId === conversationId)); setActivities(timeline) } }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'No fue posible cargar la conversación')) }, [tenantId, conversationId])
  useEffect(load, [load])
  async function run(operation: () => Promise<unknown>) { try { await operation(); load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Operación rechazada') } }
  if (!item) return <div className="page">{error ? <div className="error-banner">{error}</div> : <div className="loading-state">Cargando conversación…</div>}</div>
  return <div className="page"><Link to="/conversations" className="back-link"><ArrowLeft size={15} /> Volver a conversaciones</Link><div className="detail-hero"><div><div className="detail-kicker"><SampleBadge /><span>{tenantNames[tenantId]} · {item.channel}</span></div><h1>{customer?.name || 'Conversación'}</h1><div className="detail-meta"><StatusPill value={item.status} /><span>{item.assignedMode}</span><span>{item.assignedUserId || item.automationAgent || 'Sin asignar'}</span></div></div></div><div className="info-banner">Mensajería externa aún no conectada. Solo se muestra metadata operacional.</div>
    {error && <div className="error-banner">{error}</div>}<div className="transition-bar"><div><span>Estado operacional</span><small>Reabrir y escalar son acciones explícitas.</small></div>{item.status !== 'CLOSED' && item.status !== 'HUMAN_REQUIRED' && <button className="secondary-button" onClick={() => void run(() => sampleCommercialApp.requireHumanConversation(tenantId, conversationId))}><UserRoundCheck size={15} /> Requerir humano</button>}{item.status === 'HUMAN_REQUIRED' && <button className="primary-button" onClick={() => void run(() => sampleCommercialApp.assignHumanConversation(tenantId, conversationId, 'platform-owner'))}><UserRoundCheck size={15} /> Asignarme</button>}{item.status !== 'CLOSED' ? <button className="secondary-button danger" onClick={() => void run(() => sampleCommercialApp.closeConversation(tenantId, conversationId))}><X size={15} /> Cerrar</button> : <button className="primary-button" onClick={() => void run(() => sampleCommercialApp.reopenConversation(tenantId, conversationId))}><RotateCcw size={15} /> Reabrir</button>}</div>
    <div className="detail-grid"><section className="panel detail-panel"><div className="section-heading"><div><span className="eyebrow">Metadata</span><h2>Conversación</h2></div></div><div className="overview-grid"><Info label="Cliente" value={customer?.name || '—'} /><Info label="Negocio" value={tenantNames[tenantId]} /><Info label="Canal" value={item.channel} /><Info label="Estado" value={item.status} /><Info label="Modo asignado" value={item.assignedMode} /><Info label="Iniciada" value={date(item.startedAt)} /><Info label="Última actividad" value={date(item.lastActivityAt)} /><Info label="Cerrada" value={date(item.closedAt)} /></div></section><section className="panel detail-panel"><div className="section-heading"><div><span className="eyebrow">Vínculos</span><h2>Oportunidades</h2></div></div><div className="stack-list">{opportunities.length ? opportunities.map((opportunity) => <Link className="mini-card" to={`/opportunities/${tenantId}/${opportunity.id}`} key={opportunity.id}><div><StatusPill value={opportunity.status} /><strong>{opportunity.intent.replaceAll('_',' ')}</strong></div><b>{money(opportunity.estimatedValueCents)}</b></Link>) : <p className="muted-copy">Sin oportunidades vinculadas.</p>}</div></section></div>
    <section className="panel detail-panel"><div className="section-heading"><div><span className="eyebrow">Actividad comercial</span><h2>Timeline</h2></div></div><div className="stack-list">{activities.length ? activities.map((activity) => <article className="timeline-item" key={activity.id}><span /><div><strong>{activity.summary || activity.type}</strong><small>{activity.actorType} · {date(activity.occurredAt)}</small></div></article>) : <p className="muted-copy">Sin actividad vinculada.</p>}</div></section>
  </div>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="info-block"><span>{label}</span><strong>{value}</strong></div> }
