import type { AuditEvent, CommercialActivity, CommercialAgreement, CommercialNote, CommercialTask, Conversation, Customer, CustomerIdentity, CustomerStatus, HumanEscalation, IdempotencyRecord, IdempotentOperation, InventoryPosition, InventoryReservation, ManagedSale, Opportunity, OpportunityStatus, Order, Payment, PaymentProof, Settlement, Tenant } from '../domain/index.js'

export interface TenantRepository { list(): Promise<readonly Tenant[]>; getById(id: string): Promise<Tenant | null> }
export interface CustomerRepository { listByTenant(tenantId: string, filters?: { search?: string; status?: CustomerStatus }): Promise<readonly Customer[]>; getById(tenantId: string, id: string): Promise<Customer | null>; save(tenantId: string, customer: Customer): Promise<void> }
export interface CustomerIdentityRepository { listByCustomer(tenantId: string, customerId: string): Promise<readonly CustomerIdentity[]>; resolve(tenantId: string, channel: CustomerIdentity['channel'], externalIdentifier: string): Promise<CustomerIdentity | null>; save(tenantId: string, identity: CustomerIdentity): Promise<void> }
export interface ConversationRepository { listByTenant(tenantId: string, filters?: { status?: Conversation['status']; channel?: Conversation['channel']; humanRequired?: boolean }): Promise<readonly Conversation[]>; getById(tenantId: string, id: string): Promise<Conversation | null>; save(tenantId: string, conversation: Conversation): Promise<void> }
export interface OpportunityRepository { listByTenant(tenantId: string, filters?: { status?: OpportunityStatus; customerId?: string }): Promise<readonly Opportunity[]>; getById(tenantId: string, id: string): Promise<Opportunity | null>; save(tenantId: string, opportunity: Opportunity): Promise<void> }
export interface CommercialActivityRepository { listByTenant(tenantId: string, filters?: { customerId?: string; opportunityId?: string; conversationId?: string; orderId?: string; paymentId?: string }): Promise<readonly CommercialActivity[]>; append(tenantId: string, activity: CommercialActivity): Promise<void> }
export interface CommercialNoteRepository { listByCustomer(tenantId: string, customerId: string): Promise<readonly CommercialNote[]>; save(tenantId: string, note: CommercialNote): Promise<void> }
export interface CommercialTaskRepository { listByTenant(tenantId: string, filters?: { customerId?: string; status?: CommercialTask['status'] }): Promise<readonly CommercialTask[]>; getById(tenantId: string, id: string): Promise<CommercialTask | null>; save(tenantId: string, task: CommercialTask): Promise<void> }
export interface OrderRepository { listByTenant(tenantId: string, filters?: { orderStatus?: Order['orderStatus']; paymentStatus?: Order['paymentStatus']; fulfillmentStatus?: Order['fulfillmentStatus']; managed?: boolean; search?: string }): Promise<readonly Order[]>; getById(tenantId: string, id: string): Promise<Order | null>; getByOpportunity(tenantId: string, opportunityId: string): Promise<Order | null>; save(tenantId: string, order: Order): Promise<void> }
export interface PaymentRepository { listByTenant(tenantId: string, filters?: { status?: Payment['status'] }): Promise<readonly Payment[]>; getById(tenantId: string, id: string): Promise<Payment | null>; getByOrder(tenantId: string, orderId: string): Promise<Payment | null>; save(tenantId: string, payment: Payment): Promise<void> }
export interface PaymentProofRepository { listByTenant(tenantId: string, filters?: { status?: PaymentProof['status']; orderId?: string }): Promise<readonly PaymentProof[]>; getById(tenantId: string, id: string): Promise<PaymentProof | null>; save(tenantId: string, proof: PaymentProof): Promise<void> }
export interface InventoryRepository { getPosition(tenantId: string, productId: string, variantId?: string): Promise<InventoryPosition | null> }
export interface InventoryReservationRepository { listByTenant(tenantId: string, filters?: { status?: InventoryReservation['status'] }): Promise<readonly InventoryReservation[]>; getById(tenantId: string, id: string): Promise<InventoryReservation | null>; getByOrder(tenantId: string, orderId: string): Promise<InventoryReservation | null>; save(tenantId: string, reservation: InventoryReservation): Promise<void> }
export interface IdempotencyRepository { get(tenantId: string, operation: IdempotentOperation, key: string): Promise<IdempotencyRecord | null>; save(tenantId: string, record: IdempotencyRecord): Promise<void> }
export interface AgreementRepository { getEffective(tenantId: string, at: string): Promise<CommercialAgreement | null> }
export interface ManagedSaleRepository { list(tenantId: string): Promise<readonly ManagedSale[]>; save(sale: ManagedSale): Promise<void> }
export interface EscalationRepository { listOpen(tenantId: string): Promise<readonly HumanEscalation[]>; save(tenantId: string, escalation: HumanEscalation): Promise<void> }
export interface SettlementRepository { list(tenantId: string): Promise<readonly Settlement[]>; save(settlement: Settlement): Promise<void> }
export interface AuditRepository { listByTenant(tenantId: string, filters?: { entityType?: string; entityId?: string }): Promise<readonly AuditEvent[]>; append(tenantId: string, event: AuditEvent): Promise<void> }
