import { ArrowLeft, Check, Plus } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { sampleCommercialApp } from '../../application/sampleApp'
import type { CustomerDetail } from '../../application/commercial'
import type { TaskPriority } from '../../domain'
import { OPEN_PIPELINE_STATUSES } from '../../domain'
import { date, money, tenantNames } from '../commercial/formatters'
import { EmptyState, SampleBadge, StatusPill } from '../commercial/shared'

type Tab = 'OVERVIEW' | 'OPPORTUNITIES' | 'CONVERSATIONS' | 'ACTIVITY' | 'NOTES' | 'TASKS'
export function CustomerDetailPage() {
  const { tenantId = '', customerId = '' } = useParams()
  const [detail, setDetail] = useState<CustomerDetail | null>(null)
  const [tab, setTab] = useState<Tab>('OVERVIEW')
  const [error, setError] = useState('')
  const [action, setAction] = useState<'OPPORTUNITY' | 'NOTE' | 'TASK' | null>(null)
  const load = useCallback(() => { setError(''); void sampleCommercialApp.getCustomerDetail(tenantId, customerId).then(setDetail).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'No fue posible cargar el cliente')) }, [tenantId, customerId])
  useEffect(() => {
  queueMicrotask(load)
}, [load])
  const open = useMemo(() => detail?.opportunities.filter((item) => OPEN_PIPELINE_STATUSES.includes(item.status)) ?? [], [detail])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { if (action === 'OPPORTUNITY') await sampleCommercialApp.createOpportunity({ tenantId, customerId, intent: 'PURCHASE_INTENT', estimatedValueCents: Math.round(Number(data.get('value')) * 100), currency: String(data.get('currency')).trim().toUpperCase(), acquisitionSource: detail?.customer.acquisitionSource }); if (action === 'NOTE') await sampleCommercialApp.addCommercialNote({ tenantId, customerId, authorId: 'platform-owner', body: String(data.get('body')) }); if (action === 'TASK') await sampleCommercialApp.createCommercialTask({ tenantId, customerId, title: String(data.get('title')), priority: String(data.get('priority')) as TaskPriority, dueAt: String(data.get('dueAt')) ? new Date(String(data.get('dueAt'))).toISOString() : undefined }); setAction(null); load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible completar la acción') } }
  async function complete(id: string) { try { await sampleCommercialApp.completeCommercialTask(tenantId, id); load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible completar la tarea') } }
  if (!detail) return <div className="page">{error ? <div className="error-banner">{error}</div> : <div className="loading-state">Cargando cliente…</div>}</div>
  const { customer } = detail
  return <div className="page"><Link to="/customers" className="back-link"><ArrowLeft size={15} /> Volver a clientes</Link><div className="detail-hero"><div><div className="detail-kicker"><SampleBadge /><span>{tenantNames[tenantId]}</span></div><h1>{customer.name}</h1><div className="detail-meta"><StatusPill value={customer.status} /><span>{customer.email || 'Sin email'}</span><span>{customer.phone || 'Sin teléfono'}</span></div><div className="tag-list">{customer.tags?.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="detail-stats"><div><span>Oportunidades abiertas</span><strong>{open.length}</strong></div><div><span>Pipeline estimado</span><strong>{money(open.reduce((sum, item) => sum + item.estimatedValueCents, 0))}</strong></div><div><span>Última interacción</span><strong>{date(customer.lastInteractionAt)}</strong></div></div></div>
    <div className="action-bar"><button onClick={() => setAction('OPPORTUNITY')}><Plus size={15} /> Crear oportunidad</button><button onClick={() => setAction('NOTE')}><Plus size={15} /> Añadir nota</button><button onClick={() => setAction('TASK')}><Plus size={15} /> Crear tarea</button></div>
    {action && <form className="inline-form compact-form panel" onSubmit={submit}><div><span className="eyebrow">Acción comercial</span><h2>{action === 'OPPORTUNITY' ? 'Nueva oportunidad' : action === 'NOTE' ? 'Nueva nota' : 'Nueva tarea'}</h2></div>{action === 'OPPORTUNITY' && <label className="field"><span>Valor estimado (COP)</span><input name="value" type="number" min="0" step="1" required /></label>}{action === 'NOTE' && <label className="field grow"><span>Nota</span><textarea name="body" required /></label>}{action === 'TASK' && <><label className="field grow"><span>Título</span><input name="title" required /></label><label className="field"><span>Prioridad</span><select name="priority" defaultValue="NORMAL"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label className="field"><span>Vence</span><input name="dueAt" type="datetime-local" /></label></>}<button className="primary-button" type="submit">Guardar</button><button className="secondary-button" type="button" onClick={() => setAction(null)}>Cancelar</button></form>}
    {error && <div className="error-banner" role="alert">{error}</div>}
    <div className="tabs" role="tablist" aria-label="Detalle del cliente">{(['OVERVIEW','OPPORTUNITIES','CONVERSATIONS','ACTIVITY','NOTES','TASKS'] as Tab[]).map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{item.replace('_',' ')}</button>)}</div>
    <section className="panel detail-panel">{tab === 'OVERVIEW' && <div className="overview-grid"><Info label="Estado" value={customer.status} /><Info label="Origen" value={customer.acquisitionSource || '—'} /><Info label="Creado" value={date(customer.createdAt)} /><Info label="Actualizado" value={date(customer.updatedAt)} /></div>}{tab === 'OPPORTUNITIES' && <Cards items={detail.opportunities.map((item) => <Link className="mini-card" key={item.id} to={`/opportunities/${item.tenantId}/${item.id}`}><div><StatusPill value={item.status} /><strong>{item.intent.replaceAll('_',' ')}</strong><small>{date(item.lastActivityAt)}</small></div><b>{money(item.estimatedValueCents)}</b></Link>)} empty="No hay oportunidades." />}{tab === 'CONVERSATIONS' && <Cards items={detail.conversations.map((item) => <Link className="mini-card" key={item.id} to={`/conversations/${item.tenantId}/${item.id}`}><div><StatusPill value={item.status} /><strong>{item.channel}</strong><small>{item.assignedMode}</small></div><b>{date(item.lastActivityAt)}</b></Link>)} empty="No hay conversaciones." />}{tab === 'ACTIVITY' && <Cards items={detail.activities.map((item) => <article className="timeline-item" key={item.id}><span /><div><strong>{item.summary || item.type.replaceAll('_',' ')}</strong><small>{item.actorType} · {date(item.occurredAt)}</small></div></article>)} empty="Aún no hay actividad." />}{tab === 'NOTES' && <Cards items={detail.notes.map((item) => <article className="note-card" key={item.id}><p>{item.body}</p><small>{item.authorId} · {date(item.createdAt)}</small></article>)} empty="Aún no hay notas." />}{tab === 'TASKS' && <Cards items={detail.tasks.map((item) => <article className="task-card" key={item.id}><div><StatusPill value={item.status} /><strong>{item.title}</strong><small>{item.priority} · vence {date(item.dueAt)}</small></div>{item.status === 'OPEN' && <button className="secondary-button" onClick={() => void complete(item.id)}><Check size={14} /> Completar</button>}</article>)} empty="No hay tareas." />}</section>
  </div>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="info-block"><span>{label}</span><strong>{value}</strong></div> }
function Cards({ items, empty }: { items: React.ReactNode[]; empty: string }) { return items.length ? <div className="stack-list">{items}</div> : <EmptyState title={empty} body="Las nuevas acciones se registrarán en este espacio." /> }
