import { useCallback,useEffect,useState } from 'react'
import { useParams } from 'react-router-dom'
const stores={floes:{tenant:'tenant-floes',name:'FLOES'},mg:{tenant:'tenant-mg',name:'MG Salud y Belleza'},dgng:{tenant:'tenant-dgng',name:'DGNG'}} as const
type Dashboard={orders:number;paymentsToVerify:number;ordersToPrepare:number;readyToDispatch:number}
type Order={id:string;createdAt:string;paymentStatus:string;fulfillmentStatus:string;orderStatus:string;grandTotalCents:number;currency:string;items:readonly {productName:string;variantName?:string;quantity:number}[];customer?:{name:string;phone?:string}|null}
type Review={proof:{id:string;paymentId:string;orderId:string;assetReference?:string};order:Order;payment:{id:string}}
const money=(value:number,currency:string)=>new Intl.NumberFormat('es-CO',{style:'currency',currency,maximumFractionDigits:0}).format(value/100)
const humanStatus=(order:Order)=>order.orderStatus==='CANCELLED'?'Cancelado':order.fulfillmentStatus==='DELIVERED'?'Entregado':order.fulfillmentStatus==='DISPATCHED'?'Despachado':order.fulfillmentStatus==='READY'?'Listo para despacho':order.fulfillmentStatus==='PREPARING'?'Preparando':order.paymentStatus==='PAID'?'Pago aprobado':order.paymentStatus==='REJECTED'?'Pago rechazado':['PROOF_RECEIVED','UNDER_REVIEW'].includes(order.paymentStatus)?'Pago por verificar':'Esperando pago'
export function OwnerPanelPage(){
 const {storeSlug='floes'}=useParams();const store=stores[storeSlug as keyof typeof stores]??stores.floes;const tenant=store.tenant;const [access,setAccess]=useState(()=>sessionStorage.getItem(`chopify-owner-access:${tenant}`)??'');const [authenticated,setAuthenticated]=useState(()=>Boolean(sessionStorage.getItem(`chopify-owner-access:${tenant}`)))
 const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [orders,setOrders]=useState<readonly Order[]>([]);const [reviews,setReviews]=useState<readonly Review[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('')
 const call=useCallback(async(operation:string,input:Record<string,unknown>={})=>{const response=await fetch('/api/commerce',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${access}`,'x-chopify-tenant-id':tenant,'x-chopify-access-scope':'owner'},body:JSON.stringify({operation,input,idempotencyKey:`owner:${operation}:${Date.now()}`})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(response.status===401?'La clave de acceso no es válida.':body.error||'No fue posible completar la acción');return body.data},[access,tenant])
 const load=useCallback(async()=>{if(!access)return;setLoading(true);setError('');try{const [summary,list,pending]=await Promise.all([call('ownerDashboard'),call('listOrders'),call('listPaymentReviews')]);setDashboard(summary);setOrders(list);setReviews(pending)}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible cargar la operación')}finally{setLoading(false)}},[access,call])
 useEffect(()=>{if(!authenticated)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[authenticated,load])
 const enter=async()=>{sessionStorage.setItem(`chopify-owner-access:${tenant}`,access);setAuthenticated(true)}
 const action=async(operation:string,input:Record<string,unknown>)=>{setError('');try{await call(operation,input);await load()}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible completar la acción')}}
 if(!authenticated)return <main className="owner-login"><section><span className="owner-mark">CHOPIFY OPERACIONES</span><h1>Tu tienda, al día.</h1><p>Ingresa con la clave entregada a tu equipo.</p><label>Clave de acceso<input type="password" value={access} onChange={event=>setAccess(event.target.value)} autoComplete="current-password"/></label><button onClick={()=>void enter()} disabled={!access.trim()}>Entrar</button>{error&&<p className="owner-error">{error}</p>}</section></main>
 return <main className="owner-page"><header><div><span className="owner-mark">{store.name} · OPERACIÓN</span><h1>Hoy</h1></div></header>{error&&<div className="owner-error">{error}</div>}
 <section className="owner-metrics"><article><strong>{dashboard?.paymentsToVerify??0}</strong><span>Pagos por verificar</span></article><article><strong>{dashboard?.ordersToPrepare??0}</strong><span>Por preparar</span></article><article><strong>{dashboard?.readyToDispatch??0}</strong><span>Por despachar</span></article><article><strong>{dashboard?.orders??0}</strong><span>Pedidos</span></article></section>
 <section className="owner-section"><div className="owner-section-title"><h2>Pagos por verificar</h2><button className="owner-secondary" onClick={()=>void load()} disabled={loading}>Actualizar</button></div>{!loading&&reviews.length===0?<p className="owner-empty">No hay pagos pendientes de revisión.</p>:reviews.map(({proof,order,payment})=><article className="owner-order urgent" key={proof.id}><div><small>Pedido {order.id}</small><h3>{order.customer?.name??'Cliente'} · {money(order.grandTotalCents,order.currency)}</h3>{proof.assetReference?<a href={proof.assetReference} target="_blank" rel="noreferrer">Ver comprobante</a>:<p>El comprobante no incluye un archivo consultable.</p>}</div><div className="owner-actions"><button onClick={()=>void action('approvePayment',{paymentId:payment.id,proofId:proof.id})}>Aprobar pago</button><button className="owner-danger" onClick={()=>{const reason=window.prompt('Motivo para solicitar revisión');if(reason?.trim())void action('rejectPaymentProof',{paymentId:payment.id,proofId:proof.id,reason})}}>Rechazar / revisar</button></div></article>)}</section>
 <section className="owner-section"><h2>Pedidos</h2>{!loading&&orders.length===0?<p className="owner-empty">Todavía no hay pedidos reales en esta tienda.</p>:orders.map(order=><article className="owner-order" key={order.id}><div><small>{new Date(order.createdAt).toLocaleString('es-CO')}</small><h3>{order.customer?.name??'Cliente'} · {money(order.grandTotalCents,order.currency)}</h3><p>{order.items.map(item=>`${item.quantity}× ${item.productName}${item.variantName?` · ${item.variantName}`:''}`).join(', ')}</p><span className="owner-status">{humanStatus(order)}</span></div><div className="owner-actions">{order.paymentStatus==='PAID'&&order.fulfillmentStatus==='UNFULFILLED'&&<button onClick={()=>void action('startPreparation',{orderId:order.id})}>Empezar preparación</button>}{order.fulfillmentStatus==='PREPARING'&&<button onClick={()=>void action('markReady',{orderId:order.id})}>Marcar listo</button>}{order.fulfillmentStatus==='READY'&&<button onClick={()=>{const courier=window.prompt('Transportista (opcional)')??'';const trackingCode=window.prompt('Número de guía (opcional)')??'';void action('dispatchOrder',{orderId:order.id,courier,trackingCode})}}>Marcar despachado</button>}{order.fulfillmentStatus==='DISPATCHED'&&<button onClick={()=>void action('markDelivered',{orderId:order.id})}>Marcar entregado</button>}</div></article>)}</section></main>
}
