import { ArrowLeft, CheckCircle2, RotateCcw, ShoppingCart, Sparkles, XCircle } from 'lucide-react'
import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { sampleCommercialApp } from '../../application/sampleApp'
import type { CommercialActivity, Customer, Opportunity, OpportunityLossReason } from '../../domain'
import { date, money, SampleBadge, StatusPill, tenantNames } from '../commercial/shared'

export function OpportunityDetailPage() {
  const { tenantId = '', opportunityId = '' } = useParams()
  const [item, setItem] = useState<Opportunity | null>(null)
  const [customer, setCustomer] = useState<Customer | null>(null)
  const [activities, setActivities] = useState<readonly CommercialActivity[]>([])
  const [error, setError] = useState('')
  const [form, setForm] = useState<'VALUE' | 'LOSE' | 'ABANDON' | null>(null)
  const load = useCallback(() => { setError(''); void sampleCommercialApp.getOpportunity(tenantId, opportunityId).then(async (next) => { setItem(next); if (next) { const [detail, nextActivities] = await Promise.all([sampleCommercialApp.getCustomerDetail(tenantId, next.customerId), sampleCommercialApp.listCommercialActivities(tenantId, { opportunityId })]); setCustomer(detail?.customer ?? null); setActivities(nextActivities) } }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'No fue posible cargar la oportunidad')) }, [tenantId, opportunityId])
  useEffect(load, [load])
  async function run(operation: () => Promise<unknown>) { try { await operation(); setForm(null); load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Transición rechazada') } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); if (form === 'VALUE') await run(() => sampleCommercialApp.updateOpportunityEstimatedValue(tenantId, opportunityId, Math.round(Number(data.get('value')) * 100))); if (form === 'LOSE') await run(() => sampleCommercialApp.loseOpportunity(tenantId, opportunityId, String(data.get('reason')) as OpportunityLossReason, String(data.get('detail')) || undefined)); if (form === 'ABANDON') await run(() => sampleCommercialApp.abandonOpportunity(tenantId, opportunityId, String(data.get('reason')) || undefined)) }
  if (!item) return <div className="page">{error ? <div className="error-banner">{error}</div> : <div className="loading-state">Cargando oportunidad…</div>}</div>
  const primary = item.status === 'OPEN' ? { label: 'Calificar', icon: Sparkles, action: () => sampleCommercialApp.qualifyOpportunity(tenantId, opportunityId) } : item.status === 'QUALIFIED' ? { label: 'Iniciar carrito', icon: ShoppingCart, action: () => sampleCommercialApp.startOpportunityCart(tenantId, opportunityId) } : item.status === 'CART_STARTED' ? { label: 'Marcar ORDER CREATED', icon: CheckCircle2, action: () => sampleCommercialApp.markOpportunityOrderCreated(tenantId, opportunityId) } : item.status === 'ORDER_CREATED' ? { label: 'Marcar ganada', icon: CheckCircle2, action: () => sampleCommercialApp.winOpportunity(tenantId, opportunityId) } : item.status === 'ABANDONED' ? { label: 'Reabrir', icon: RotateCcw, action: () => sampleCommercialApp.reopenOpportunity(tenantId, opportunityId) } : null
  const canExit = ['OPEN','QUALIFIED','CART_STARTED'].includes(item.status)
  return <div className="page"><Link to="/opportunities" className="back-link"><ArrowLeft size={15} /> Volver a oportunidades</Link><div className="detail-hero opportunity-hero"><div><div className="detail-kicker"><SampleBadge /><span>{tenantNames[tenantId]}</span></div><h1>{customer?.name ?? 'Oportunidad'}</h1><div className="detail-meta"><StatusPill value={item.status} /><span>{item.intent.replaceAll('_',' ')}</span><span>{item.assignedTo || 'Sin asignar'}</span></div></div><div className="value-block"><span>Valor estimado</span><strong>{money(item.estimatedValueCents, item.currency)}</strong><button onClick={() => setForm('VALUE')}>Editar valor</button></div></div>
    <div className="transition-bar"><div><span>Próxima acción válida</span><small>Las transiciones son validadas por dominio.</small></div>{primary && <button className="primary-button" onClick={() => void run(primary.action)}><primary.icon size={16} /> {primary.label}</button>}{canExit && <><button className="secondary-button danger" onClick={() => setForm('LOSE')}><XCircle size={15} /> Perder</button><button className="secondary-button" onClick={() => setForm('ABANDON')}>Abandonar</button></>}</div>
    {item.status === 'ORDER_CREATED' && <div className="info-banner">ORDER_CREATED es una etapa comercial. H2 no creó un Order real.</div>}{error && <div className="error-banner" role="alert">{error}</div>}
    {form && <form className="inline-form compact-form panel" onSubmit={submit}><div><span className="eyebrow">Actualizar oportunidad</span><h2>{form === 'VALUE' ? 'Valor estimado' : form === 'LOSE' ? 'Registrar pérdida' : 'Registrar abandono'}</h2></div>{form === 'VALUE' && <label className="field"><span>Valor (COP)</span><input name="value" type="number" min="0" defaultValue={item.estimatedValueCents / 100} required /></label>}{form === 'LOSE' && <><label className="field"><span>Razón</span><select name="reason" defaultValue="PRICE"><option>PRICE</option><option>NO_STOCK</option><option>NO_RESPONSE</option><option>CUSTOMER_CHANGED_MIND</option><option>DELIVERY</option><option>PAYMENT</option><option>COMPETITOR</option><option>NOT_QUALIFIED</option><option>DUPLICATE</option><option>OTHER</option></select></label><label className="field grow"><span>Detalle (obligatorio para OTHER)</span><input name="detail" /></label></>}{form === 'ABANDON' && <label className="field grow"><span>Razón opcional</span><input name="reason" /></label>}<button className="primary-button" type="submit">Confirmar</button><button className="secondary-button" type="button" onClick={() => setForm(null)}>Cancelar</button></form>}
    <div className="detail-grid"><section className="panel detail-panel"><div className="section-heading"><div><span className="eyebrow">Contexto</span><h2>Datos comerciales</h2></div></div><div className="overview-grid"><Info label="Cliente" value={customer?.name || '—'} /><Info label="Negocio" value={tenantNames[tenantId]} /><Info label="Origen" value={item.acquisitionSource || '—'} /><Info label="Canal de conversión" value={item.conversionChannel || '—'} /><Info label="Conversación" value={item.conversationId || 'No vinculada'} /><Info label="Creada" value={date(item.createdAt)} /><Info label="Última actividad" value={date(item.lastActivityAt)} /><Info label="Asignada a" value={item.assignedTo || '—'} />{item.lostReason && <Info label="Razón de pérdida" value={`${item.lostReason}${item.lostReasonDetail ? ` · ${item.lostReasonDetail}` : ''}`} />}{item.abandonedReason && <Info label="Razón de abandono" value={item.abandonedReason} />}</div></section><section className="panel detail-panel"><div className="section-heading"><div><span className="eyebrow">Timeline</span><h2>Actividad comercial</h2></div></div><div className="stack-list">{activities.map((activity) => <article className="timeline-item" key={activity.id}><span /><div><strong>{activity.summary || activity.type}</strong><small>{activity.actorType} · {date(activity.occurredAt)}</small></div></article>)}</div></section></div>
  </div>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="info-block"><span>{label}</span><strong>{value}</strong></div> }
