import { ArrowRight, Columns3, List, Search } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { sampleCommercialApp } from '../../application/sampleApp'
import type { Customer, Opportunity } from '../../domain'
import { useUIStore } from '../../stores/uiStore'
import { date, EmptyState, money, operationalStatuses, SampleBadge, StatusPill, statusLabel, tenantNames, TenantFilter } from '../commercial/shared'

export function OpportunitiesPage() {
  const scope = useUIStore((state) => state.tenantScope)
  const [items, setItems] = useState<readonly Opportunity[]>([])
  const [customers, setCustomers] = useState<readonly Customer[]>([])
  const [view, setView] = useState<'PIPELINE' | 'LIST'>('PIPELINE')
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const load = useCallback(() => { setLoading(true); setError(''); void Promise.all([sampleCommercialApp.listOpportunities(scope), sampleCommercialApp.listCustomers(scope)]).then(([opportunities, nextCustomers]) => { setItems(opportunities); setCustomers(nextCustomers) }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'No fue posible cargar oportunidades')).finally(() => setLoading(false)) }, [scope])
  useEffect(load, [load])
  const customerByKey = useMemo(() => new Map(customers.map((item) => [`${item.tenantId}:${item.id}`, item])), [customers])
  const filtered = items.filter((item) => { const customer = customerByKey.get(`${item.tenantId}:${item.customerId}`); return !query || `${customer?.name} ${item.intent} ${item.status}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()) })
  const closed = filtered.filter((item) => !operationalStatuses.includes(item.status))
  const card = (item: Opportunity) => { const customer = customerByKey.get(`${item.tenantId}:${item.customerId}`); return <Link className="opportunity-card" key={`${item.tenantId}-${item.id}`} to={`/opportunities/${item.tenantId}/${item.id}`}><div className="opportunity-card-top"><span>{tenantNames[item.tenantId]}</span><ArrowRight size={14} /></div><strong>{customer?.name ?? 'Cliente'}</strong><small>{item.intent.replaceAll('_',' ')}</small><b>{money(item.estimatedValueCents, item.currency)}</b><footer><span>{date(item.lastActivityAt)}</span><span>{item.assignedTo || 'Sin asignar'}</span></footer></Link> }
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Commercial pipeline</span><h1>Oportunidades</h1><p>Etapas explícitas, valor estimado y resultados separados. Ninguna etapa crea todavía un pedido real.</p></div><div className="heading-actions"><SampleBadge /><TenantFilter /></div></div>
    <div className="filter-bar"><label className="search-field"><Search size={16} /><span className="sr-only">Buscar oportunidades</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar cliente, intención o estado" /></label><div className="view-switch" aria-label="Vista"><button className={view === 'PIPELINE' ? 'active' : ''} onClick={() => setView('PIPELINE')}><Columns3 size={15} /> Pipeline</button><button className={view === 'LIST' ? 'active' : ''} onClick={() => setView('LIST')}><List size={15} /> Lista</button></div></div>
    {error && <div className="error-banner">{error} <button onClick={load}>Reintentar</button></div>}{loading ? <div className="loading-state">Cargando pipeline…</div> : filtered.length === 0 ? <EmptyState title="No hay oportunidades" body="Cambia los filtros o crea una desde el detalle de un cliente." /> : view === 'PIPELINE' ? <><div className="pipeline-board">{operationalStatuses.map((status) => { const stageItems = filtered.filter((item) => item.status === status); return <section className="pipeline-column" key={status}><header><div><span>{statusLabel(status)}</span><strong>{stageItems.length}</strong></div><small>{money(stageItems.reduce((sum, item) => sum + item.estimatedValueCents, 0))}</small></header><div>{stageItems.map(card)}{stageItems.length === 0 && <span className="column-empty">Sin oportunidades</span>}</div></section> })}</div><section className="closed-section"><div className="section-heading"><div><span className="eyebrow">Resultados</span><h2>Cerradas y abandonadas</h2></div><span>{closed.length}</span></div><div className="closed-grid">{closed.map((item) => <Link to={`/opportunities/${item.tenantId}/${item.id}`} className="closed-card" key={item.id}><StatusPill value={item.status} /><strong>{customerByKey.get(`${item.tenantId}:${item.customerId}`)?.name}</strong><span>{money(item.estimatedValueCents)}</span></Link>)}</div></section></> : <section className="panel data-panel"><div className="responsive-table opportunity-table"><div className="table-row table-labels"><span>Customer</span><span>Business</span><span>Status</span><span>Intent</span><span>Value</span><span>Last activity</span><span /></div>{filtered.map((item) => <div className="table-row" key={item.id}><strong>{customerByKey.get(`${item.tenantId}:${item.customerId}`)?.name}</strong><span data-label="Business">{tenantNames[item.tenantId]}</span><span data-label="Status"><StatusPill value={item.status} /></span><span data-label="Intent">{item.intent.replaceAll('_',' ')}</span><strong data-label="Value">{money(item.estimatedValueCents)}</strong><span data-label="Last activity">{date(item.lastActivityAt)}</span><Link className="row-link" to={`/opportunities/${item.tenantId}/${item.id}`}><ArrowRight size={16} /></Link></div>)}</div></section>}
  </div>
}
