import { describe,expect,it } from 'vitest'
import { createSampleAutomationRepositories } from '../adapters/memory/automationRepositories'
import type { AutomationEvent } from '../domain'
import { AutomationApplication } from './automation'
const owner={actorId:'platform-owner',role:'PLATFORM_OWNER' as const}
const floesEvent=(id='evt-1'):AutomationEvent=>({id,tenantId:'tenant-floes',type:'PAYMENT_CONFIRMED',occurredAt:'2026-09-27T18:00:00.000Z',entityType:'ORDER',entityId:'order-fl-1',orderId:'order-fl-1',customerId:'cus-fl-1',conversationId:'conv-fl-1',data:{channel:'WHATSAPP'}})
describe('H4 automation application',()=>{
 it('creates tenant-scoped outbox actions for FLOES',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r);const items=await app.processEvent(floesEvent(),owner);expect(items).toHaveLength(2);expect(items.every(x=>x.tenantId==='tenant-floes')).toBe(true)})
 it('is idempotent for the same event/rule/action',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r);await app.processEvent(floesEvent(),owner);const again=await app.processEvent(floesEvent(),owner);expect(again).toHaveLength(0);expect(await r.outbox.listByTenant('tenant-floes')).toHaveLength(2)})
 it('does not leak FLOES events into MG',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r);await app.processEvent(floesEvent(),owner);expect(await r.outbox.listByTenant('tenant-mg')).toHaveLength(0)})
 it('rejects a cross-tenant actor',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r);await expect(app.processEvent(floesEvent(),{actorId:'mg',role:'TENANT_OWNER',tenantId:'tenant-mg'})).rejects.toThrow('Actor tenant mismatch')})
 it('dispatches pending outbox successfully',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r);const [item]=await app.processEvent(floesEvent(),owner);const done=await app.dispatch(item.tenantId,item.id,owner);expect(done.status).toBe('SENT');expect(done.attempts).toBe(1)})
 it('records failure and permits retry',async()=>{const r=createSampleAutomationRepositories();let fail=true;const app=new AutomationApplication(r,{execute:async()=>{if(fail)throw new Error('temporary');}});const [item]=await app.processEvent(floesEvent(),owner);const first=await app.dispatch(item.tenantId,item.id,owner);expect(first.status).toBe('FAILED');fail=false;const second=await app.dispatch(item.tenantId,item.id,owner);expect(second.status).toBe('SENT');expect(second.attempts).toBe(2)})
 it('dead-letters after maximum attempts',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r,{execute:async()=>{throw new Error('down')}});const [item]=await app.processEvent(floesEvent(),owner);await app.dispatch(item.tenantId,item.id,owner);await app.dispatch(item.tenantId,item.id,owner);const third=await app.dispatch(item.tenantId,item.id,owner);expect(third.status).toBe('DEAD_LETTER')})
 it('can pause a rule without affecting another tenant',async()=>{const r=createSampleAutomationRepositories();const app=new AutomationApplication(r);const before=await r.definitions.getById('tenant-floes','auto-fl-paid');await app.toggle('tenant-floes','auto-fl-paid',owner);const after=await r.definitions.getById('tenant-floes','auto-fl-paid');expect(before?.status).toBe('ACTIVE');expect(after?.status).toBe('PAUSED');expect((await r.definitions.getById('tenant-mg','auto-mg-paid'))?.status).toBe('ACTIVE')})
})
