import type { ActorContext, CommerceProduct, Customer, Order, PaymentProof } from '../domain'
import type { CommercialApplication } from './commercial'
import type { OrderApplication } from './orders'
import type { BusinessCommerceAdapter } from './commercePort'

export type CommerceGatewayOperation = 'searchProducts'|'getProductDetails'|'checkAvailability'|'createOrUpdateCustomer'|'createOpportunity'|'createOrderDraft'|'attachPaymentProof'|'getOrderStatus'
export interface CommerceGatewayRequest { operation: CommerceGatewayOperation; tenantId: string; input: Record<string, unknown>; idempotencyKey?: string; correlationId?: string; requestId?: string }

const money=(cents:number,currency:string)=>({amount:cents/100,currency})
const product=(item:CommerceProduct)=>({productId:item.id,name:item.name,description:undefined,price:money(item.priceCents,item.currency),available:item.fulfillmentMode==='MADE_TO_ORDER'||item.fulfillmentMode==='SERVICE'||item.available>0,imageUrl:item.imageUrl,metadata:{fulfillmentMode:item.fulfillmentMode,variantId:item.variantId,variantName:item.variantName}})
const customer=(item:Customer)=>({customerId:item.id,name:item.name,phone:item.phone,email:item.email})
const actor=(tenantId:string):ActorContext=>({actorId:'ganobot-commerce',role:'AUTOMATION',tenantId})
const requiredString=(value:unknown,label:string)=>{if(typeof value!=='string'||!value.trim())throw new Error(`${label} is required`);return value.trim()}
const optionalString=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():undefined
const status=(order:Order)=>({orderId:order.id,status:order.orderStatus==='CANCELLED'?'cancelled':order.fulfillmentStatus==='DELIVERED'?'delivered':order.fulfillmentStatus==='DISPATCHED'?'dispatched':order.fulfillmentStatus==='PREPARING'||order.fulfillmentStatus==='READY'?'preparing':order.paymentStatus==='PAID'?'paid':order.paymentStatus==='PROOF_RECEIVED'||order.paymentStatus==='UNDER_REVIEW'?'payment-under-review':order.orderStatus==='CREATED'?'draft':'awaiting-payment',paymentStatus:order.paymentStatus==='PAID'?'approved':order.paymentStatus==='REJECTED'?'rejected':order.paymentStatus==='PROOF_RECEIVED'||order.paymentStatus==='UNDER_REVIEW'?'pending_review':'unpaid',fulfillmentStatus:order.fulfillmentStatus==='DELIVERED'?'delivered':order.fulfillmentStatus==='DISPATCHED'?'dispatched':order.fulfillmentStatus==='PREPARING'||order.fulfillmentStatus==='READY'?'preparing':'unfulfilled',total:money(order.grandTotalCents,order.currency)})

export class CommerceGateway {
 constructor(private commercial:CommercialApplication,private orders:OrderApplication,private commerce:BusinessCommerceAdapter){}
 async execute(request:CommerceGatewayRequest):Promise<unknown>{
  const {tenantId,input}=request
  switch(request.operation){
   case 'searchProducts': {const q=optionalString(input.query)??'';const limit=typeof input.limit==='number'?Math.max(1,Math.min(20,Math.floor(input.limit))):10;return (await this.commerce.searchProducts(tenantId,q)).slice(0,limit).map(product)}
   case 'getProductDetails': {const p=await this.commerce.getProduct(tenantId,requiredString(input.productId,'productId'));return p?product(p):undefined}
   case 'checkAvailability': {const productId=requiredString(input.productId,'productId');const variantId=optionalString(input.variantId);const p=await this.commerce.getProduct(tenantId,productId,variantId);if(!p)return{productId,variantId,available:false,availableQuantity:0,reason:'not_found'};const quantity=typeof input.quantity==='number'?Math.max(1,Math.floor(input.quantity)):1;const available=await this.commerce.getAvailability(tenantId,productId,variantId);const canFulfill=p.fulfillmentMode==='MADE_TO_ORDER'||p.fulfillmentMode==='SERVICE'||available>=quantity;return{productId,variantId,available:canFulfill,availableQuantity:available,reason:canFulfill?undefined:'insufficient_stock'}}
   case 'createOrUpdateCustomer': {const customerId=optionalString(input.customerId);if(customerId){const existing=await this.commercial.getCustomerDetail(tenantId,customerId);if(existing){return customer(await this.commercial.updateCustomer(tenantId,customerId,{name:optionalString(input.name)??existing.customer.name,phone:optionalString(input.phone),email:optionalString(input.email),acquisitionSource:optionalString(input.channel)}))}}const name=optionalString(input.name)??optionalString(input.phone)??optionalString(input.email)??'Cliente';return customer(await this.commercial.createCustomer({tenantId,name,phone:optionalString(input.phone),email:optionalString(input.email),acquisitionSource:optionalString(input.channel)}))}
   case 'createOpportunity': {const customerId=requiredString(input.customerId,'customerId');const ids=Array.isArray(input.productIds)?input.productIds.filter((v):v is string=>typeof v==='string'):[];let cents=0,currency='USD';if(ids[0]){const p=await this.commerce.getProduct(tenantId,ids[0]);if(p){cents=p.priceCents;currency=p.currency}}const o=await this.commercial.createOpportunity({tenantId,customerId,intent:'PURCHASE_INTENT',estimatedValueCents:cents,currency,acquisitionSource:optionalString(input.source),conversionChannel:optionalString(input.source),assignedTo:'ganobot'});return{opportunityId:o.id,customerId:o.customerId,status:'new'}}
   case 'createOrderDraft': {const customerId=requiredString(input.customerId,'customerId');let opportunityId=optionalString(input.opportunityId);if(!opportunityId){const o=await this.commercial.createOpportunity({tenantId,customerId,intent:'PURCHASE_INTENT',estimatedValueCents:0,currency:'USD',assignedTo:'ganobot'});opportunityId=o.id}let o=await this.commercial.getOpportunity(tenantId,opportunityId);if(!o)throw new Error('Opportunity not found in tenant');if(o.status==='OPEN')o=await this.commercial.qualifyOpportunity(tenantId,o.id);if(o.status==='QUALIFIED')o=await this.commercial.startOpportunityCart(tenantId,o.id);if(o.status==='CART_STARTED')o=await this.commercial.markOpportunityOrderCreated(tenantId,o.id);const lines=Array.isArray(input.lines)?input.lines:[];const items=lines.map((line)=>{if(typeof line!=='object'||!line)throw new Error('Invalid order line');const r=line as Record<string,unknown>;const quantity=typeof r.quantity==='number'?Math.floor(r.quantity):0;if(quantity<1)throw new Error('quantity must be positive');return{productId:requiredString(r.productId,'productId'),variantId:optionalString(r.variantId),quantity}});const order=await this.orders.createOrderFromOpportunity({tenantId,opportunityId:o.id,items,managed:true,managedBy:'AUTOMATION',idempotencyKey:request.idempotencyKey??`${tenantId}:${request.requestId??o.id}:createOrderDraft`,actor:actor(tenantId)});return{orderId:order.id,status:'draft',customerId:order.customerId,total:money(order.grandTotalCents,order.currency)}}
   case 'attachPaymentProof': {const orderId=requiredString(input.orderId,'orderId');const proof:PaymentProof=await this.orders.submitPaymentProof({tenantId,orderId,reference:optionalString(input.externalReference),assetReference:optionalString(input.proofUrl),idempotencyKey:request.idempotencyKey??`${tenantId}:${request.requestId??orderId}:attachPaymentProof`,actor:actor(tenantId)});return{proofId:proof.id,orderId:proof.orderId,status:'pending_review'}}
   case 'getOrderStatus': {const order=await this.orders.getOrder(tenantId,requiredString(input.orderId,'orderId'));return order?status(order):undefined}
  }
 }
}
