import { describe,expect,it } from 'vitest'
import { createTenantCommerceState,MemoryCommerceStateStore,migrateCommerceState,PersistentCommerceRuntime,tenantDefinitions } from './commerceRuntime.js'
const req=(operation:Parameters<PersistentCommerceRuntime['execute']>[0]['operation'],input:Record<string,unknown>,id='r1',tenantId='tenant-floes')=>({operation,tenantId,input,requestId:id,correlationId:`c-${id}`,idempotencyKey:`idem-${id}`})
const mgProduct={id:'mg-real-1',tenantId:'tenant-mg',sku:'MG-REAL-1',slug:'producto-real',name:'Producto real',description:'',commercialSummary:'',category:'General',status:'ACTIVE',visibility:'VISIBLE',pricingStatus:'READY',costCents:null,percentage:null,percentageType:null,salePriceCents:10000,currency:'COP',fulfillmentMode:'MADE_TO_ORDER',images:[],variants:[]}
const seedMg=(runtime:PersistentCommerceRuntime,id='seed')=>runtime.execute(req('updateProduct',{product:mgProduct},id,'tenant-mg'))
describe('Persistent Commerce Runtime production state',()=>{
 it('starts MG and DGNG empty and FLOES with only the canonical catalog',()=>{expect(createTenantCommerceState('tenant-mg').orders.products).toHaveLength(0);expect(createTenantCommerceState('tenant-dgng').orders.products).toHaveLength(0);const floes=createTenantCommerceState('tenant-floes');expect(floes.orders.products).toHaveLength(4);expect(JSON.stringify(floes)).not.toMatch(/SAMPLE|example\.test|sample:\/\//i)})
 it('formalizes tenant lifecycle and rejects unknown tenants',()=>{expect(tenantDefinitions['tenant-floes'].status).toBe('ACTIVE');expect(tenantDefinitions['tenant-mg'].status).toBe('ONBOARDING');expect(tenantDefinitions['tenant-dgng'].status).toBe('ONBOARDING');expect(tenantDefinitions['tenant-floes'].currency).toBe('USD');expect(tenantDefinitions['tenant-mg'].currency).toBe('USD');expect(tenantDefinitions['tenant-dgng'].currency).toBe('USD');expect(()=>createTenantCommerceState('tenant-foreign')).toThrow('Unknown tenant')})
 it('never deletes a same-tenant record because its content looks like a fixture',()=>{const legacy=createTenantCommerceState('tenant-mg');legacy.commercial.customers.push({id:'sample-customer-legitimate',tenantId:'tenant-mg',name:'Sample Comercial SAS',email:'owner@example.test',status:'ACTIVE',createdAt:'2026-10-01T00:00:00.000Z',updatedAt:'2026-10-01T00:00:00.000Z'});const migrated=migrateCommerceState('tenant-mg',{...legacy,schemaVersion:2});expect(migrated.commercial.customers.map(item=>item.id)).toEqual(['sample-customer-legitimate'])})
 it('rejects a cross-tenant state instead of silently deleting or exposing it',()=>{const legacy=createTenantCommerceState('tenant-mg');legacy.commercial.customers.push({id:'foreign',tenantId:'tenant-dgng',name:'Foreign',status:'ACTIVE',createdAt:'2026-10-01T00:00:00.000Z',updatedAt:'2026-10-01T00:00:00.000Z'});expect(()=>migrateCommerceState('tenant-mg',{...legacy,schemaVersion:2})).toThrow('cross-tenant customers')})
 it('persists customers and enforces tenant isolation',async()=>{const store=new MemoryCommerceStateStore();const runtime=new PersistentCommerceRuntime(store);const customer=await runtime.execute(req('createOrUpdateCustomer',{name:'Solo FLOES'},'customer')) as {customerId:string};const restarted=new PersistentCommerceRuntime(store);const opportunity=await restarted.execute(req('createOpportunity',{customerId:customer.customerId,source:'WEB'},'opp')) as {customerId:string};expect(opportunity.customerId).toBe(customer.customerId);await expect(restarted.execute(req('createOpportunity',{customerId:customer.customerId},'wrong','tenant-mg'))).rejects.toThrow('Customer not found in tenant')})
 it('keeps proof pending until human approval and completes fulfillment',async()=>{const runtime=new PersistentCommerceRuntime(new MemoryCommerceStateStore());await seedMg(runtime);const customer=await runtime.execute(req('createOrUpdateCustomer',{name:'Cliente real'},'c','tenant-mg')) as {customerId:string};const order=await runtime.execute(req('createOrderDraft',{customerId:customer.customerId,lines:[{productId:'mg-real-1',quantity:1}]},'o','tenant-mg')) as {orderId:string};const proof=await runtime.execute(req('attachPaymentProof',{orderId:order.orderId,proofUrl:'https://files.example.com/proof'},'p','tenant-mg')) as {proofId:string;paymentId:string;status:string};expect(proof.status).toBe('pending_review');expect((await runtime.execute(req('getOrderStatus',{orderId:order.orderId},'s','tenant-mg')) as {paymentStatus:string}).paymentStatus).toBe('pending_review');await runtime.execute(req('approvePayment',{paymentId:proof.paymentId,proofId:proof.proofId},'a','tenant-mg'));await runtime.execute(req('startPreparation',{orderId:order.orderId},'prep','tenant-mg'));await runtime.execute(req('markReady',{orderId:order.orderId},'ready','tenant-mg'));await runtime.execute(req('dispatchOrder',{orderId:order.orderId,courier:'Transportista real',trackingCode:'GUIA-1'},'ship','tenant-mg'));const delivered=await runtime.execute(req('markDelivered',{orderId:order.orderId},'done','tenant-mg')) as {status:string};expect(delivered.status).toBe('delivered')})
 it('rejects proof without approving the order',async()=>{const runtime=new PersistentCommerceRuntime(new MemoryCommerceStateStore());await seedMg(runtime);const customer=await runtime.execute(req('createOrUpdateCustomer',{name:'Cliente revisión'},'rc','tenant-mg')) as {customerId:string};const order=await runtime.execute(req('createOrderDraft',{customerId:customer.customerId,lines:[{productId:'mg-real-1',quantity:1}]},'ro','tenant-mg')) as {orderId:string};const proof=await runtime.execute(req('attachPaymentProof',{orderId:order.orderId},'rp','tenant-mg')) as {proofId:string;paymentId:string};await runtime.execute(req('rejectPaymentProof',{paymentId:proof.paymentId,proofId:proof.proofId,reason:'No coincide'},'rr','tenant-mg'));expect((await runtime.execute(req('getOrderStatus',{orderId:order.orderId},'rs','tenant-mg')) as {paymentStatus:string}).paymentStatus).toBe('rejected')})
 it('returns tenant-scoped owner reads',async()=>{const runtime=new PersistentCommerceRuntime(new MemoryCommerceStateStore());expect(await runtime.execute(req('ownerDashboard',{},'d','tenant-mg'))).toMatchObject({orders:0,paymentsToVerify:0});expect(await runtime.execute(req('listOrders',{},'l','tenant-mg'))).toEqual([]);expect(await runtime.execute(req('listPaymentReviews',{},'r','tenant-mg'))).toEqual([])})
})
