import type { CommercialActivity, CommercialActivityType, CommercialNote, CommercialTask, Conversation, Customer, CustomerStatus, Opportunity, OpportunityIntent, OpportunityLossReason, TaskPriority } from '../domain/index.js'
import { abandonOpportunity as abandon, assignHumanConversation, assignOpportunity as assign, calculateConversionMetrics, cancelTask as cancel, closeConversation as close, completeTask as complete, createCommercialNote, loseOpportunity as lose, markOpportunityOrderCreated as markOrderCreated, projectAttention, projectPipeline, qualifyOpportunity as qualify, reopenConversation as reopenConversationDomain, reopenOpportunity as reopen, requireHumanConversation as requireHuman, startOpportunityCart as startCart, updateOpportunityEstimatedValue as updateValue, winOpportunity as win } from '../domain/index.js'
import type { CommercialActivityRepository, CommercialNoteRepository, CommercialTaskRepository, ConversationRepository, CustomerIdentityRepository, CustomerRepository, EscalationRepository, OpportunityRepository, TenantRepository } from '../repositories/contracts.js'

export type TenantScope = string | 'ALL'
export interface CommercialRepositories {
  tenants: TenantRepository; customers: CustomerRepository; identities: CustomerIdentityRepository; conversations: ConversationRepository
  opportunities: OpportunityRepository; activities: CommercialActivityRepository; notes: CommercialNoteRepository; tasks: CommercialTaskRepository; escalations: EscalationRepository
}
export interface CustomerDetail { customer: Customer; opportunities: readonly Opportunity[]; conversations: readonly Conversation[]; activities: readonly CommercialActivity[]; notes: readonly CommercialNote[]; tasks: readonly CommercialTask[] }

export class CommercialApplication {
  private sequence = 100
  constructor(private readonly repositories: CommercialRepositories, private readonly clock: () => string = () => new Date().toISOString()) {}
  private id(prefix: string) { this.sequence += 1; const uuid = globalThis.crypto?.randomUUID?.(); return uuid ? `${prefix}-${uuid}` : `${prefix}-${Date.now()}-${this.sequence}` }
  private async tenantIds(scope: TenantScope) { const tenants = await this.repositories.tenants.list(); if (scope === 'ALL') return tenants.map((item) => item.id); if (!tenants.some((item) => item.id === scope)) throw new Error('Unknown tenant'); return [scope] }
  private async aggregate<T>(scope: TenantScope, query: (tenantId: string) => Promise<readonly T[]>): Promise<T[]> { const ids = await this.tenantIds(scope); return (await Promise.all(ids.map(query))).flat() }
  private async activity(tenantId: string, customerId: string, type: CommercialActivityType, summary: string, links: { opportunityId?: string; conversationId?: string } = {}) { const occurredAt = this.clock(); await this.repositories.activities.append(tenantId, { id: this.id('activity'), tenantId, customerId, type, actorType: 'PLATFORM_USER', actorId: 'platform-owner', occurredAt, summary, ...links }) }

  listTenants() { return this.repositories.tenants.list() }
  listCustomers(scope: TenantScope, filters?: { search?: string; status?: CustomerStatus }) { return this.aggregate(scope, (tenantId) => this.repositories.customers.listByTenant(tenantId, filters)) }
  async getCustomerDetail(tenantId: string, customerId: string): Promise<CustomerDetail | null> { const customer = await this.repositories.customers.getById(tenantId, customerId); if (!customer) return null; const [opportunities, conversations, activities, notes, tasks] = await Promise.all([this.repositories.opportunities.listByTenant(tenantId, { customerId }), this.repositories.conversations.listByTenant(tenantId).then((items) => items.filter((item) => item.customerId === customerId)), this.repositories.activities.listByTenant(tenantId, { customerId }), this.repositories.notes.listByCustomer(tenantId, customerId), this.repositories.tasks.listByTenant(tenantId, { customerId })]); return { customer, opportunities, conversations, activities, notes, tasks } }
  async createCustomer(input: { tenantId: string; name: string; phone?: string; email?: string; status?: CustomerStatus; acquisitionSource?: string; tags?: readonly string[] }) { if (!input.name.trim()) throw new Error('Customer name is required'); await this.tenantIds(input.tenantId); const now = this.clock(); const customer: Customer = { ...input, id: this.id('customer'), name: input.name.trim(), status: input.status ?? 'LEAD', createdAt: now, updatedAt: now, lastInteractionAt: now }; await this.repositories.customers.save(input.tenantId, customer); await this.activity(input.tenantId, customer.id, 'CUSTOMER_CREATED', 'Cliente creado'); return customer }
  async updateCustomer(tenantId: string, customerId: string, changes: Partial<Pick<Customer, 'name' | 'phone' | 'email' | 'status' | 'acquisitionSource' | 'tags'>>) { const current = await this.requireCustomer(tenantId, customerId); const next = { ...current, ...changes, id: current.id, tenantId, name: (changes.name ?? current.name).trim(), updatedAt: this.clock() }; if (!next.name) throw new Error('Customer name is required'); await this.repositories.customers.save(tenantId, next); await this.activity(tenantId, customerId, 'CUSTOMER_UPDATED', 'Cliente actualizado'); return next }

  listConversations(scope: TenantScope, filters?: Parameters<ConversationRepository['listByTenant']>[1]) { return this.aggregate(scope, (tenantId) => this.repositories.conversations.listByTenant(tenantId, filters)) }
  getConversation(tenantId: string, id: string) { return this.repositories.conversations.getById(tenantId, id) }
  async startConversation(input: { tenantId: string; customerId: string; channel: Conversation['channel']; assignedMode?: Conversation['assignedMode'] }) { await this.requireCustomer(input.tenantId, input.customerId); const now = this.clock(); const item: Conversation = { id: this.id('conversation'), tenantId: input.tenantId, customerId: input.customerId, channel: input.channel, status: 'OPEN', assignedMode: input.assignedMode ?? 'HUMAN', startedAt: now, lastActivityAt: now, createdAt: now, updatedAt: now }; await this.repositories.conversations.save(input.tenantId, item); await this.activity(input.tenantId, input.customerId, 'CONVERSATION_STARTED', 'Conversación iniciada', { conversationId: item.id }); return item }
  async requireHumanConversation(tenantId: string, id: string) { const item = await this.requireConversation(tenantId, id); const next = requireHuman(item, this.clock()); await this.repositories.conversations.save(tenantId, next); await this.activity(tenantId, item.customerId, 'CONVERSATION_ESCALATED', 'Conversación requiere atención humana', { conversationId: id }); return next }
  async assignHumanConversation(tenantId: string, id: string, userId: string) { const item = await this.requireConversation(tenantId, id); const next = assignHumanConversation(item, userId, this.clock()); await this.repositories.conversations.save(tenantId, next); return next }
  async closeConversation(tenantId: string, id: string) { const item = await this.requireConversation(tenantId, id); const next = close(item, this.clock()); await this.repositories.conversations.save(tenantId, next); await this.activity(tenantId, item.customerId, 'CONVERSATION_CLOSED', 'Conversación cerrada', { conversationId: id }); return next }
  async reopenConversation(tenantId: string, id: string) { const item = await this.requireConversation(tenantId, id); const next = reopenConversationDomain(item, this.clock()); await this.repositories.conversations.save(tenantId, next); await this.activity(tenantId, item.customerId, 'CONVERSATION_STARTED', 'Conversación reabierta explícitamente', { conversationId: id }); return next }

  listOpportunities(scope: TenantScope, filters?: Parameters<OpportunityRepository['listByTenant']>[1]) { return this.aggregate(scope, (tenantId) => this.repositories.opportunities.listByTenant(tenantId, filters)) }
  getOpportunity(tenantId: string, id: string) { return this.repositories.opportunities.getById(tenantId, id) }
  async createOpportunity(input: { tenantId: string; customerId: string; conversationId?: string; intent: OpportunityIntent; estimatedValueCents: number; currency: string; acquisitionSource?: string; conversionChannel?: string; assignedTo?: string }) { await this.requireCustomer(input.tenantId, input.customerId); if (input.conversationId) { const conversation = await this.requireConversation(input.tenantId, input.conversationId); if (conversation.customerId !== input.customerId) throw new Error('Conversation and customer must match') } if (!Number.isInteger(input.estimatedValueCents) || input.estimatedValueCents < 0) throw new Error('Estimated value must be a non-negative integer in cents'); if(!/^[A-Z]{3}$/.test(input.currency))throw new Error('Opportunity currency must be explicit'); const now = this.clock(); const item: Opportunity = { ...input, id: this.id('opportunity'), status: 'OPEN', createdAt: now, updatedAt: now, lastActivityAt: now }; await this.repositories.opportunities.save(input.tenantId, item); await this.activity(input.tenantId, input.customerId, 'OPPORTUNITY_CREATED', 'Oportunidad creada', { opportunityId: item.id }); return item }
  qualifyOpportunity(tenantId: string, id: string) { return this.transition(tenantId, id, (item, at) => qualify(item, at), 'OPPORTUNITY_QUALIFIED', 'Oportunidad calificada') }
  startOpportunityCart(tenantId: string, id: string) { return this.transition(tenantId, id, (item, at) => startCart(item, at), 'OPPORTUNITY_STAGE_CHANGED', 'Etapa comercial: CART_STARTED') }
  markOpportunityOrderCreated(tenantId: string, id: string) { return this.transition(tenantId, id, (item, at) => markOrderCreated(item, at), 'OPPORTUNITY_STAGE_CHANGED', 'Etapa comercial: ORDER_CREATED (sin crear pedido)') }
  winOpportunity(tenantId: string, id: string) { return this.transition(tenantId, id, (item, at) => win(item, at), 'OPPORTUNITY_WON', 'Oportunidad ganada') }
  loseOpportunity(tenantId: string, id: string, reason: OpportunityLossReason, detail?: string) { return this.transition(tenantId, id, (item, at) => lose(item, reason, at, detail), 'OPPORTUNITY_LOST', `Oportunidad perdida: ${reason}`) }
  abandonOpportunity(tenantId: string, id: string, reason?: string) { return this.transition(tenantId, id, (item, at) => abandon(item, at, reason), 'OPPORTUNITY_ABANDONED', 'Oportunidad abandonada') }
  reopenOpportunity(tenantId: string, id: string) { return this.transition(tenantId, id, (item, at) => reopen(item, at), 'OPPORTUNITY_REOPENED', 'Oportunidad reabierta explícitamente') }
  assignOpportunity(tenantId: string, id: string, assignedTo: string) { return this.transition(tenantId, id, (item, at) => assign(item, assignedTo, at), 'OPPORTUNITY_ASSIGNED', `Asignada a ${assignedTo}`) }
  updateOpportunityEstimatedValue(tenantId: string, id: string, cents: number) { return this.transition(tenantId, id, (item, at) => updateValue(item, cents, at), 'OPPORTUNITY_VALUE_CHANGED', 'Valor estimado actualizado') }
  private async transition(tenantId: string, id: string, change: (item: Opportunity, at: string) => Opportunity, type: CommercialActivityType, summary: string) { const item = await this.requireOpportunity(tenantId, id); const next = change(item, this.clock()); await this.repositories.opportunities.save(tenantId, next); await this.activity(tenantId, item.customerId, type, summary, { opportunityId: id }); return next }

  async addCommercialNote(input: { tenantId: string; customerId: string; opportunityId?: string; authorId: string; body: string }) { await this.requireCustomer(input.tenantId, input.customerId); if (input.opportunityId) { const opportunity = await this.requireOpportunity(input.tenantId, input.opportunityId); if (opportunity.customerId !== input.customerId) throw new Error('Note customer and opportunity must match') } const note = createCommercialNote({ ...input, id: this.id('note'), createdAt: this.clock() }); await this.repositories.notes.save(input.tenantId, note); await this.activity(input.tenantId, input.customerId, 'NOTE_ADDED', 'Nota comercial añadida', { opportunityId: input.opportunityId }); return note }
  listCommercialActivities(tenantId: string, filters?: Parameters<CommercialActivityRepository['listByTenant']>[1]) { return this.repositories.activities.listByTenant(tenantId, filters) }
  async createCommercialTask(input: { tenantId: string; title: string; priority: TaskPriority; customerId?: string; opportunityId?: string; conversationId?: string; dueAt?: string; assignedTo?: string }) { const title = input.title.trim(); if (!title) throw new Error('Task title is required'); let customerId = input.customerId; if (customerId) await this.requireCustomer(input.tenantId, customerId); if (input.opportunityId) { const opportunity = await this.requireOpportunity(input.tenantId, input.opportunityId); customerId ??= opportunity.customerId; if (customerId !== opportunity.customerId) throw new Error('Task customer and opportunity must match') } if (input.conversationId) { const conversation = await this.requireConversation(input.tenantId, input.conversationId); customerId ??= conversation.customerId; if (customerId !== conversation.customerId) throw new Error('Task customer and conversation must match') } const task: CommercialTask = { ...input, id: this.id('task'), title, customerId, status: 'OPEN', createdAt: this.clock() }; await this.repositories.tasks.save(input.tenantId, task); if (customerId) await this.activity(input.tenantId, customerId, 'TASK_CREATED', `Tarea creada: ${title}`, { opportunityId: input.opportunityId, conversationId: input.conversationId }); return task }
  async completeCommercialTask(tenantId: string, id: string) { const item = await this.requireTask(tenantId, id); const next = complete(item, this.clock()); await this.repositories.tasks.save(tenantId, next); if (item.customerId) await this.activity(tenantId, item.customerId, 'TASK_COMPLETED', `Tarea completada: ${item.title}`, { opportunityId: item.opportunityId, conversationId: item.conversationId }); return next }
  async cancelCommercialTask(tenantId: string, id: string) { const item = await this.requireTask(tenantId, id); const next = cancel(item); await this.repositories.tasks.save(tenantId, next); if (item.customerId) await this.activity(tenantId, item.customerId, 'TASK_CANCELLED', `Tarea cancelada: ${item.title}`, { opportunityId: item.opportunityId, conversationId: item.conversationId }); return next }

  async loadDashboard(scope: TenantScope) { const ids = await this.tenantIds(scope); const [tenants, opportunities, conversations, tasks, escalationGroups] = await Promise.all([this.repositories.tenants.list(), this.listOpportunities(scope), this.listConversations(scope), this.aggregate(scope, (id) => this.repositories.tasks.listByTenant(id)), Promise.all(ids.map((id) => this.repositories.escalations.listOpen(id)))]); const relevantTenants = scope === 'ALL' ? tenants : tenants.filter((item) => item.id === scope); return { dataMode: 'SAMPLE' as const, tenants: relevantTenants, pipeline: projectPipeline(opportunities), conversions: calculateConversionMetrics(opportunities), attention: projectAttention(escalationGroups.flat(), conversations, tasks, this.clock()) } }

  private async requireCustomer(tenantId: string, id: string) { const item = await this.repositories.customers.getById(tenantId, id); if (!item) throw new Error('Customer not found in tenant'); return item }
  private async requireConversation(tenantId: string, id: string) { const item = await this.repositories.conversations.getById(tenantId, id); if (!item) throw new Error('Conversation not found in tenant'); return item }
  private async requireOpportunity(tenantId: string, id: string) { const item = await this.repositories.opportunities.getById(tenantId, id); if (!item) throw new Error('Opportunity not found in tenant'); return item }
  private async requireTask(tenantId: string, id: string) { const item = await this.repositories.tasks.getById(tenantId, id); if (!item) throw new Error('Task not found in tenant'); return item }
}
