import type { ActorContext, Attribution, AuditEvent, CommercialActivity, CommercialActivityType, CommercialAgreementSnapshot, IdempotentOperation, InventoryReservation, Order, OrderItemRequest, Payment, PaymentProof } from '../domain'
import { approvePayment, approveProof, authorizeTenant, calculateManagementFee, calculateManagedRevenue, calculateOrderTotals, cancelOrder as cancelOrderDomain, commitReservation, createOrderItemSnapshot, dispatchOrder as dispatchDomain, expireReservation, markDelivered as deliveredDomain, markReady as readyDomain, receivePaymentProof, startPaymentReview as startPaymentReviewDomain, rejectPayment, rejectProof, releaseReservation, startPreparation as preparationDomain, winOpportunity } from '../domain'
import type { BusinessCommerceAdapter } from './commercePort'
import type { AgreementRepository, AuditRepository, CommercialActivityRepository, CustomerRepository, IdempotencyRepository, InventoryReservationRepository, OpportunityRepository, OrderRepository, PaymentProofRepository, PaymentRepository, TenantRepository } from '../repositories/contracts'
import type { TenantScope } from './commercial'

export interface OrderApplicationRepositories { tenants: TenantRepository; customers: CustomerRepository; opportunities: OpportunityRepository; activities: CommercialActivityRepository; orders: OrderRepository; payments: PaymentRepository; proofs: PaymentProofRepository; reservations: InventoryReservationRepository; idempotency: IdempotencyRepository; agreements: AgreementRepository; audit: AuditRepository; commerce: BusinessCommerceAdapter }
export interface OrderDetail { order: Order; payment: Payment; proofs: readonly PaymentProof[]; reservation: InventoryReservation | null; activities: readonly CommercialActivity[]; audit: readonly AuditEvent[] }
export class OrderApplication {
  private sequence = 500
  constructor(private readonly repositories: OrderApplicationRepositories, private readonly clock: () => string = () => new Date().toISOString()) {}
  private id(prefix: string) { this.sequence += 1; return `${prefix}-${this.sequence}` }
  private actorType(actor: ActorContext) { return actor.role === 'AUTOMATION' ? 'AUTOMATION' as const : actor.role === 'SYSTEM' ? 'SYSTEM' as const : actor.role === 'PLATFORM_OWNER' ? 'PLATFORM_USER' as const : 'TENANT_USER' as const }
  private key(key: string) { if (!key.trim()) throw new Error('Idempotency key is required'); return key.trim() }
  private async tenantIds(scope: TenantScope) { const tenants = await this.repositories.tenants.list(); if (scope === 'ALL') return tenants.map((item) => item.id); if (!tenants.some((item) => item.id === scope)) throw new Error('Unknown tenant'); return [scope] }
  private async previousIdempotency(tenantId: string, operation: IdempotentOperation, key: string) {
    const normalizedKey = this.key(key)
    const existing = await this.repositories.idempotency.get(tenantId, operation, normalizedKey)
    if (existing?.status === 'STARTED') throw new Error('Operation already in progress or requires recovery')
    return existing?.status === 'COMPLETED' ? existing : null
  }
  private async startIdempotency(tenantId: string, operation: IdempotentOperation, key: string) { const now = this.clock(); await this.repositories.idempotency.save(tenantId, { tenantId, operation, key: this.key(key), status: 'STARTED', createdAt: now }) }
  private async completeIdempotency(tenantId: string, operation: IdempotentOperation, key: string, resultReference: string) { const existing = await this.repositories.idempotency.get(tenantId, operation, this.key(key)); await this.repositories.idempotency.save(tenantId, { tenantId, operation, key: this.key(key), status: 'COMPLETED', resultReference, createdAt: existing?.createdAt ?? this.clock(), completedAt: this.clock() }) }
  private async record(order: Order, type: CommercialActivityType, summary: string, actor: ActorContext, links: { paymentId?: string } = {}) { const at = this.clock(); await this.repositories.activities.append(order.tenantId, { id: this.id('activity'), tenantId: order.tenantId, customerId: order.customerId, opportunityId: order.opportunityId, conversationId: order.conversationId, orderId: order.id, type, actorType: this.actorType(actor), actorId: actor.actorId, occurredAt: at, summary, ...links }); await this.repositories.audit.append(order.tenantId, { id: this.id('audit'), tenantId: order.tenantId, entityType: 'ORDER', entityId: order.id, type, actorType: this.actorType(actor), actorId: actor.actorId, timestamp: at }) }

  async listOrders(scope: TenantScope, filters?: Parameters<OrderRepository['listByTenant']>[1]) { const ids = await this.tenantIds(scope); return (await Promise.all(ids.map((tenantId) => this.repositories.orders.listByTenant(tenantId, filters)))).flat() }
  getOrder(tenantId: string, orderId: string) { return this.repositories.orders.getById(tenantId, orderId) }
  async getOrderDetail(tenantId: string, orderId: string): Promise<OrderDetail | null> { const order = await this.repositories.orders.getById(tenantId, orderId); if (!order) return null; const [payment, proofs, reservation, activities, audit] = await Promise.all([this.repositories.payments.getByOrder(tenantId, orderId), this.repositories.proofs.listByTenant(tenantId, { orderId }), this.repositories.reservations.getByOrder(tenantId, orderId), this.repositories.activities.listByTenant(tenantId, { orderId }), this.repositories.audit.listByTenant(tenantId, { entityType: 'ORDER', entityId: orderId })]); if (!payment) throw new Error('Order payment record is missing'); return { order, payment, proofs, reservation, activities, audit } }
  searchProducts(tenantId: string, query = '') { return this.repositories.commerce.searchProducts(tenantId, query) }

  async createOrderFromOpportunity(input: { tenantId: string; opportunityId: string; items: readonly OrderItemRequest[]; shippingCents?: number; taxCents?: number; otherPassThroughCents?: number; managed?: boolean; managedBy?: Attribution['managedBy']; idempotencyKey: string; actor: ActorContext }) {
    authorizeTenant(input.actor, input.tenantId, 'order:manage'); const previous = await this.previousIdempotency(input.tenantId, 'CREATE_ORDER', input.idempotencyKey); if (previous?.resultReference) { const result = await this.repositories.orders.getById(input.tenantId, previous.resultReference); if (result) return result }
    const existing = await this.repositories.orders.getByOpportunity(input.tenantId, input.opportunityId); if (existing) return existing
    const opportunity = await this.repositories.opportunities.getById(input.tenantId, input.opportunityId); if (!opportunity || opportunity.status !== 'ORDER_CREATED') throw new Error('Opportunity must be ORDER_CREATED in this tenant')
    if (!await this.repositories.customers.getById(input.tenantId, opportunity.customerId)) throw new Error('Customer not found in tenant')
    const products = await Promise.all(input.items.map(async (request) => { const product = await this.repositories.commerce.getProduct(input.tenantId, request.productId, request.variantId); if (!product) throw new Error('Product not found in tenant commerce adapter'); return { request, product } }))
    const currencies = new Set(products.map(({ product }) => product.currency)); if (currencies.size !== 1) throw new Error('Order items must use one currency')
    const snapshots = products.map(({ product, request }) => createOrderItemSnapshot({ productId: product.id, variantId: product.variantId, productName: product.name, variantName: product.variantName, quantity: request.quantity, unitPriceCents: product.priceCents, discountCents: request.discountCents, imageUrl: product.imageUrl, externalProductId: product.externalProductId, externalVariantId: product.externalVariantId }))
    const physical = products.filter(({ product, request }) => product.fulfillmentMode === 'STOCK' || (product.fulfillmentMode === 'HYBRID' && product.available >= request.quantity)).map(({ request }) => ({ productId: request.productId, variantId: request.variantId, quantity: request.quantity }))
    const totals = calculateOrderTotals(snapshots, input); const at = this.clock(); const managed = input.managed ?? true; const managedBy = managed ? input.managedBy ?? 'HUMAN' : 'NONE'; const attributionSnapshot: Attribution = { acquisitionSource: opportunity.acquisitionSource, conversionChannel: opportunity.conversionChannel, managed, managedBy, conversationId: opportunity.conversationId }
    const agreement = managed ? await this.repositories.agreements.getEffective(input.tenantId, at) : null; const commercialAgreementSnapshot: CommercialAgreementSnapshot | undefined = agreement ? { agreementId: agreement.id, managedOrderRateBps: agreement.managedOrderRateBps, publicationFeeCents: agreement.publicationFeeCents, annualContinuityFeeCents: agreement.annualContinuityFeeCents, rulesVersion: agreement.rulesVersion, effectiveFrom: agreement.effectiveFrom, capturedAt: at } : undefined
    const base = calculateManagedRevenue({ ...totals, attributionSnapshot }); const rate = commercialAgreementSnapshot?.managedOrderRateBps ?? 0; const order: Order = { id: this.id('order'), tenantId: input.tenantId, customerId: opportunity.customerId, opportunityId: opportunity.id, conversationId: opportunity.conversationId, currency: [...currencies][0], items: snapshots, ...totals, orderStatus: 'CREATED', paymentStatus: 'UNPAID', fulfillmentStatus: 'UNFULFILLED', attributionSnapshot: Object.freeze({ ...attributionSnapshot }), commercialAgreementSnapshot: commercialAgreementSnapshot && Object.freeze({ ...commercialAgreementSnapshot }), managedSnapshot: Object.freeze({ managed, managedBy, managedOrderRateBps: rate, managedRevenueBaseCents: base, managementFeeCents: calculateManagementFee(base, rate, managed) }), createdAt: at, updatedAt: at }
    await this.startIdempotency(input.tenantId, 'CREATE_ORDER', input.idempotencyKey); if (physical.length) await this.repositories.commerce.reserveInventory(input.tenantId, physical)
    const reservation: InventoryReservation | null = physical.length ? { id: this.id('reservation'), tenantId: input.tenantId, orderId: order.id, items: physical, status: 'ACTIVE', createdAt: at, expiresAt: new Date(new Date(at).getTime() + 72 * 60 * 60 * 1000).toISOString() } : null
    const payment: Payment = { id: this.id('payment'), tenantId: input.tenantId, orderId: order.id, amountCents: order.grandTotalCents, currency: order.currency, status: 'UNPAID', createdAt: at, updatedAt: at }
    await this.repositories.orders.save(input.tenantId, order); await this.repositories.payments.save(input.tenantId, payment); if (reservation) await this.repositories.reservations.save(input.tenantId, reservation); await this.repositories.commerce.publishOrderReference(input.tenantId, order.id); await this.record(order, 'ORDER_CREATED', 'Pedido real creado desde oportunidad', input.actor); if (reservation) await this.record(order, 'INVENTORY_RESERVED', 'Inventario reservado', input.actor); await this.completeIdempotency(input.tenantId, 'CREATE_ORDER', input.idempotencyKey, order.id); return order
  }

  async submitPaymentProof(input: { tenantId: string; orderId: string; type?: PaymentProof['type']; reference?: string; assetReference?: string; idempotencyKey: string; actor: ActorContext }) { authorizeTenant(input.actor, input.tenantId, 'order:manage'); const previous = await this.previousIdempotency(input.tenantId, 'SUBMIT_PAYMENT_PROOF', input.idempotencyKey); if (previous?.resultReference) { const result = await this.repositories.proofs.getById(input.tenantId, previous.resultReference); if (result) return result } const detail = await this.requireDetail(input.tenantId, input.orderId); const at = this.clock(); const payment = receivePaymentProof(detail.payment, at); const proof: PaymentProof = { id: this.id('proof'), tenantId: input.tenantId, paymentId: payment.id, orderId: input.orderId, type: input.type ?? 'TRANSFER', reference: input.reference, assetReference: input.assetReference ?? `sample://proof/${input.orderId}`, status: 'RECEIVED', submittedAt: at }; await this.startIdempotency(input.tenantId, 'SUBMIT_PAYMENT_PROOF', input.idempotencyKey); await this.repositories.payments.save(input.tenantId, payment); await this.repositories.proofs.save(input.tenantId, proof); await this.repositories.orders.save(input.tenantId, { ...detail.order, paymentStatus: payment.status, updatedAt: at }); await this.record(detail.order, 'PAYMENT_PROOF_SUBMITTED', 'Comprobante recibido; pago aún no confirmado', input.actor, { paymentId: payment.id }); await this.completeIdempotency(input.tenantId, 'SUBMIT_PAYMENT_PROOF', input.idempotencyKey, proof.id); return proof }

  async startPaymentReview(input: { tenantId: string; paymentId: string; proofId: string; actor: ActorContext }) { authorizeTenant(input.actor, input.tenantId, 'payment:approve'); const payment = await this.requirePayment(input.tenantId, input.paymentId); const proof = await this.requireProof(input.tenantId, input.proofId); if (proof.paymentId !== payment.id) throw new Error('Proof does not belong to payment'); if (proof.orderId !== payment.orderId) throw new Error('Proof and payment must belong to the same order'); const order = await this.requireOrder(input.tenantId, payment.orderId); if (order.id !== proof.orderId) throw new Error('Proof does not belong to payment order'); const at = this.clock(); const reviewed = startPaymentReviewDomain(payment, proof, at); if (reviewed.payment === payment && reviewed.proof === proof) return reviewed; await this.repositories.payments.save(input.tenantId, reviewed.payment); await this.repositories.proofs.save(input.tenantId, reviewed.proof); const reviewedOrder: Order = { ...order, paymentStatus: reviewed.payment.status, updatedAt: at }; await this.repositories.orders.save(input.tenantId, reviewedOrder); await this.record(reviewedOrder, 'PAYMENT_REVIEW_STARTED', 'Revisión de comprobante iniciada; pago aún no confirmado', input.actor, { paymentId: payment.id }); return reviewed }

  async approvePayment(input: { tenantId: string; paymentId: string; proofId: string; idempotencyKey: string; actor: ActorContext }) { authorizeTenant(input.actor, input.tenantId, 'payment:approve'); const previous = await this.previousIdempotency(input.tenantId, 'APPROVE_PAYMENT', input.idempotencyKey); if (previous?.resultReference) { const result = await this.repositories.payments.getById(input.tenantId, previous.resultReference); if (result) return result } const payment = await this.requirePayment(input.tenantId, input.paymentId); const proof = await this.requireProof(input.tenantId, input.proofId); if (proof.paymentId !== payment.id) throw new Error('Proof does not belong to payment'); if (proof.orderId !== payment.orderId) throw new Error('Proof and payment must belong to the same order'); const order = await this.requireOrder(input.tenantId, payment.orderId); if (order.id !== proof.orderId) throw new Error('Proof does not belong to payment order'); const at = this.clock(); const paid = approvePayment(payment, input.actor.actorId, at); const approved = approveProof(proof, input.actor.actorId, at); const reservation = await this.repositories.reservations.getByOrder(input.tenantId, order.id); await this.startIdempotency(input.tenantId, 'APPROVE_PAYMENT', input.idempotencyKey); if (reservation?.status === 'ACTIVE') await this.repositories.commerce.commitInventory(input.tenantId, reservation.items); const committed = reservation?.status === 'ACTIVE' ? commitReservation(reservation, at) : reservation; const confirmed: Order = { ...order, paymentStatus: 'PAID', orderStatus: 'CONFIRMED', confirmedAt: at, updatedAt: at }; await this.repositories.payments.save(input.tenantId, paid); await this.repositories.proofs.save(input.tenantId, approved); if (committed) await this.repositories.reservations.save(input.tenantId, committed); await this.repositories.orders.save(input.tenantId, confirmed); if (order.opportunityId) { const opportunity = await this.repositories.opportunities.getById(input.tenantId, order.opportunityId); if (opportunity?.status === 'ORDER_CREATED') await this.repositories.opportunities.save(input.tenantId, winOpportunity(opportunity, at)) } await this.record(confirmed, 'PAYMENT_APPROVED', 'Pago confirmado por usuario autorizado', input.actor, { paymentId: payment.id }); if (committed) await this.record(confirmed, 'INVENTORY_COMMITTED', 'Inventario comprometido', input.actor); await this.completeIdempotency(input.tenantId, 'APPROVE_PAYMENT', input.idempotencyKey, paid.id); return paid }
  async rejectPaymentProof(input: { tenantId: string; paymentId: string; proofId: string; reason: string; idempotencyKey: string; actor: ActorContext }) { authorizeTenant(input.actor, input.tenantId, 'payment:approve'); const previous = await this.previousIdempotency(input.tenantId, 'REJECT_PAYMENT', input.idempotencyKey); if (previous?.resultReference) { const result = await this.repositories.proofs.getById(input.tenantId, previous.resultReference); if (result) return result } const payment = await this.requirePayment(input.tenantId, input.paymentId); const proof = await this.requireProof(input.tenantId, input.proofId); if (proof.paymentId !== payment.id) throw new Error('Proof does not belong to payment'); if (proof.orderId !== payment.orderId) throw new Error('Proof and payment must belong to the same order'); const order = await this.requireOrder(input.tenantId, payment.orderId); if (order.id !== proof.orderId) throw new Error('Proof does not belong to payment order'); const at = this.clock(); const rejectedPayment = rejectPayment(payment, at); const rejectedProof = rejectProof(proof, input.actor.actorId, input.reason, at); await this.startIdempotency(input.tenantId, 'REJECT_PAYMENT', input.idempotencyKey); await this.repositories.payments.save(input.tenantId, rejectedPayment); await this.repositories.proofs.save(input.tenantId, rejectedProof); await this.repositories.orders.save(input.tenantId, { ...order, paymentStatus: 'REJECTED', updatedAt: at }); await this.record(order, 'PAYMENT_REJECTED', `Comprobante rechazado: ${input.reason.trim()}`, input.actor, { paymentId: payment.id }); await this.completeIdempotency(input.tenantId, 'REJECT_PAYMENT', input.idempotencyKey, proof.id); return rejectedProof }
  async cancelOrder(input: { tenantId: string; orderId: string; reason: string; idempotencyKey: string; actor: ActorContext }) { authorizeTenant(input.actor, input.tenantId, 'order:manage'); const previous = await this.previousIdempotency(input.tenantId, 'CANCEL_ORDER', input.idempotencyKey); if (previous?.resultReference) return this.requireOrder(input.tenantId, previous.resultReference); const order = await this.requireOrder(input.tenantId, input.orderId); if (order.orderStatus === 'CANCELLED') return order; const at = this.clock(); const cancelled = cancelOrderDomain(order, input.reason, at); const reservation = await this.repositories.reservations.getByOrder(input.tenantId, order.id); await this.startIdempotency(input.tenantId, 'CANCEL_ORDER', input.idempotencyKey); if (reservation?.status === 'ACTIVE') await this.repositories.commerce.releaseInventory(input.tenantId, reservation.items); const released = reservation?.status === 'ACTIVE' ? releaseReservation(reservation, at) : reservation; if (released) await this.repositories.reservations.save(input.tenantId, released); await this.repositories.orders.save(input.tenantId, cancelled); await this.record(cancelled, 'ORDER_CANCELLED', `Pedido cancelado: ${input.reason.trim()}`, input.actor); if (released?.status === 'RELEASED') await this.record(cancelled, 'INVENTORY_RELEASED', 'Reserva liberada por cancelación', input.actor); await this.completeIdempotency(input.tenantId, 'CANCEL_ORDER', input.idempotencyKey, order.id); return cancelled }
  async expireInventoryReservation(tenantId: string, reservationId: string, actor: ActorContext) { authorizeTenant(actor, tenantId, 'order:manage'); const reservation = await this.repositories.reservations.getById(tenantId, reservationId); if (!reservation) throw new Error('Reservation not found in tenant'); if (reservation.status !== 'ACTIVE') return reservation; const at = this.clock(); const expired = expireReservation(reservation, at); await this.repositories.commerce.releaseInventory(tenantId, reservation.items); await this.repositories.reservations.save(tenantId, expired); const order = await this.requireOrder(tenantId, reservation.orderId); await this.record(order, 'INVENTORY_EXPIRED', 'Reserva expirada y liberada', actor); return expired }
  startPreparation(tenantId: string, orderId: string, actor: ActorContext) { return this.fulfillment(tenantId, orderId, actor, (order, at) => preparationDomain(order, at), 'FULFILLMENT_STARTED', 'Preparación iniciada') }
  markReady(tenantId: string, orderId: string, actor: ActorContext) { return this.fulfillment(tenantId, orderId, actor, (order, at) => readyDomain(order, at), 'FULFILLMENT_READY', 'Pedido listo') }
  dispatchOrder(tenantId: string, orderId: string, actor: ActorContext, details: { courier?: string; trackingCode?: string }) { return this.fulfillment(tenantId, orderId, actor, (order, at) => dispatchDomain(order, details, at), 'ORDER_DISPATCHED', 'Pedido despachado') }
  markDelivered(tenantId: string, orderId: string, actor: ActorContext) { return this.fulfillment(tenantId, orderId, actor, (order, at) => deliveredDomain(order, at), 'ORDER_DELIVERED', 'Pedido entregado y completado') }
  private async fulfillment(tenantId: string, orderId: string, actor: ActorContext, change: (order: Order, at: string) => Order, type: CommercialActivityType, summary: string) { authorizeTenant(actor, tenantId, 'fulfillment:manage'); const order = await this.requireOrder(tenantId, orderId); const next = change(order, this.clock()); await this.repositories.orders.save(tenantId, next); await this.record(next, type, summary, actor); return next }
  async paymentReviews(scope: TenantScope) { const ids = await this.tenantIds(scope); const proofs = (await Promise.all(ids.map((id) => this.repositories.proofs.listByTenant(id)))).flat().filter((item) => ['RECEIVED', 'UNDER_REVIEW'].includes(item.status)); return Promise.all(proofs.map(async (proof) => ({ proof, order: await this.requireOrder(proof.tenantId, proof.orderId), payment: await this.requirePayment(proof.tenantId, proof.paymentId) }))) }
  async dashboard(scope: TenantScope) { const orders = await this.listOrders(scope); const reviews = await this.paymentReviews(scope); return { orders: orders.length, paymentsToVerify: reviews.length, ordersToPrepare: orders.filter((item) => item.paymentStatus === 'PAID' && item.fulfillmentStatus === 'UNFULFILLED').length, readyToDispatch: orders.filter((item) => item.fulfillmentStatus === 'READY').length, managedRevenueBaseCents: orders.filter((item) => item.managedSnapshot.managed).reduce((sum, item) => sum + item.managedSnapshot.managedRevenueBaseCents, 0), managementFeesCents: orders.filter((item) => item.managedSnapshot.managed).reduce((sum, item) => sum + item.managedSnapshot.managementFeeCents, 0) } }
  private async requireOrder(tenantId: string, id: string) { const item = await this.repositories.orders.getById(tenantId, id); if (!item) throw new Error('Order not found in tenant'); return item }
  private async requirePayment(tenantId: string, id: string) { const item = await this.repositories.payments.getById(tenantId, id); if (!item) throw new Error('Payment not found in tenant'); return item }
  private async requireProof(tenantId: string, id: string) { const item = await this.repositories.proofs.getById(tenantId, id); if (!item) throw new Error('Payment proof not found in tenant'); return item }
  private async requireDetail(tenantId: string, orderId: string) { const order = await this.requireOrder(tenantId, orderId); const payment = await this.repositories.payments.getByOrder(tenantId, orderId); if (!payment) throw new Error('Payment record not found'); return { order, payment } }
}
